// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

// エラーの原因となっていた部分を完全に削除
// 以下はコメントアウトしています

// コントローラーを直接インポート
import HelloController from "controllers/hello_controller"
import ToggleController from "controllers/toggle_controller"

// コントローラーを登録
application.register("hello", HelloController)
application.register("toggle", ToggleController)
