# Example credentials file for EC site integration
# Copy this structure to your actual credentials file using:
# EDITOR="code --wait" bin/rails credentials:edit

# Rakuten API credentials
rakuten:
  api_key: your_rakuten_api_key_here
  affiliate_id: your_rakuten_affiliate_id_here

# Amazon Product Advertising API credentials  
amazon:
  access_key: your_amazon_access_key_here
  secret_key: your_amazon_secret_key_here
  partner_tag: your_amazon_partner_tag_here
  region: JP # Amazon region (JP for Japan)