c = Company.create_or_find_by!(name: '山川光男', kana: 'やまかわみつお', prefecture_code: 6, city: '', address: '', tel: '', fax: '', website: '')
Brand.find_or_create_by!(name: '山川光男', kana: 'やまかわみつお', company: c)
c = Company.create_or_find_by!(name: '男山酒造', kana: 'おとこやましゅぞう', prefecture_code: 6, city: '山形市', address: '八日町2-4-13', tel: '023-641-0141', fax: '023-641-0225', website: 'http://www.otokoyama.co.jp')
Brand.find_or_create_by!(name: '山男山', kana: 'やまおとこやま', company: c)
Brand.find_or_create_by!(name: '羽陽男山', kana: 'うようおとこやま', company: c)
Brand.find_or_create_by!(name: 'ナヌカ', kana: 'なぬか', company: c)
c = Company.create_or_find_by!(name: '秀鳳酒造場', kana: 'しゅうほうしゅぞうじょう', prefecture_code: 6, city: '山形市', address: '山家町1-6-6', tel: '023-641-0026', fax: '023-622-8192', website: 'https://www.shuhosyuzo.com')
Brand.find_or_create_by!(name: '十八夜', kana: 'じゅうはちや', company: c)
Brand.find_or_create_by!(name: '幻酒 翁山', kana: 'おきなさん', company: c)
Brand.find_or_create_by!(name: '秀鳳', kana: 'しゅうほう', company: c)
Brand.find_or_create_by!(name: '庄五郎', kana: 'しょうごろう', company: c)
Brand.find_or_create_by!(name: '珠韻', kana: 'しゅいん', company: c)
Brand.find_or_create_by!(name: '譲川', kana: 'ゆずりかわ', company: c)
c = Company.create_or_find_by!(name: '月山酒造', kana: 'がっさんしゅぞう', prefecture_code: 6, city: '寒河江市', address: '谷沢769-1', tel: '0237-87-1114', fax: '0237-87-1163', website: 'http://www.gassan-sake.co.jp')
Brand.find_or_create_by!(name: '銀嶺月山', kana: 'ぎんれいがっさん', company: c)
c = Company.create_or_find_by!(name: '設楽酒造店', kana: 'したらしゅぞうてん', prefecture_code: 6, city: '西村山郡', address: '西川町睦合丙674-2', tel: '0237-74-2020', fax: '0237-74-2068', website: 'http://www.shitara-syuzou.com')
Brand.find_or_create_by!(name: '一声', kana: 'ひとこえ', company: c)
c = Company.create_or_find_by!(name: '鈴木酒造', kana: 'すずきしゅぞう', prefecture_code: 6, city: '西村山郡', address: '朝日町宮宿1170', tel: '0237-67-2345', fax: '0237-67-2387', website: '')
Brand.find_or_create_by!(name: '豊龍', kana: 'ほうりゅう', company: c)
c = Company.create_or_find_by!(name: '寿虎屋酒造', kana: 'ことぶきとらやしゅぞう', prefecture_code: 6, city: '山形市', address: '中里北田93-1', tel: '023-687-2626', fax: '023-687-3301', website: 'https://kotobukitoraya.co.jp')
Brand.find_or_create_by!(name: '虎屋', kana: 'とらや', company: c)
Brand.find_or_create_by!(name: '霞城寿', kana: 'かじょうことぶき', company: c)
Brand.find_or_create_by!(name: '三百年の掟やぶり', kana: 'さんびゃくねんのおきてやぶり', company: c)
c = Company.create_or_find_by!(name: '古澤酒造', kana: 'ふるさわしゅぞう', prefecture_code: 6, city: '寒河江市', address: '丸内3-5-7', tel: '0237-86-5322', fax: '0237-86-0567', website: 'http://www.furusawa.co.jp')
Brand.find_or_create_by!(name: '紅葉盛', kana: 'こうようもり', company: c)
Brand.find_or_create_by!(name: '天風', kana: 'てんぷう', company: c)
Brand.find_or_create_by!(name: '澤正宗', kana: 'さわまさむね', company: c)
c = Company.create_or_find_by!(name: '千代寿虎屋', kana: 'ちよことぶきとらやしゅぞう', prefecture_code: 6, city: '寒河江市', address: '南町2-1-16', tel: '0237-86-6133', fax: '0237-86-9644', website: 'http://www.chiyokotobuki.com')
Brand.find_or_create_by!(name: '月夜の眠り', kana: 'つきよのねむり', company: c)
Brand.find_or_create_by!(name: '千代寿', kana: 'ちよことぶき', company: c)
Brand.find_or_create_by!(name: '寒河江之荘', kana: 'さがえのしょう', company: c)
Brand.find_or_create_by!(name: '大江錦', kana: 'おおえにしき', company: c)
c = Company.create_or_find_by!(name: '浜田', kana: 'はまだ', prefecture_code: 6, city: '米沢市', address: '窪田町藤泉943-1', tel: '0238-37-6330', fax: '0238-37-6335', website: 'https://www.okimasamune.com')
Brand.find_or_create_by!(name: '興譲', kana: 'こうじょう', company: c)
Brand.find_or_create_by!(name: '濱田', kana: 'はまだ', company: c)
Brand.find_or_create_by!(name: 'Faucon', kana: 'フォコン', company: c)
Brand.find_or_create_by!(name: '雪氷柱', kana: 'ゆきつらら', company: c)
Brand.find_or_create_by!(name: '沖正宗', kana: 'おきまさむね', company: c)
Brand.find_or_create_by!(name: '天下御免の大ふへんもの', kana: 'てんかごめんのだいふへんもの', company: c)
c = Company.create_or_find_by!(name: '小嶋総本店', kana: 'こじまそうほんてん', prefecture_code: 6, city: '米沢市', address: '本町2-2-3', tel: '0238-23-4848', fax: '0238-23-4863', website: 'https://www.sake-toko.co.jp')
Brand.find_or_create_by!(name: 'なせば成る', kana: 'なせばなる', company: c)
Brand.find_or_create_by!(name: '東光', kana: 'とうこう', company: c)
Brand.find_or_create_by!(name: '美味酒', kana: 'うまざけ', company: c)
Brand.find_or_create_by!(name: '東光正宗', kana: 'とうこうまさむね', company: c)
Brand.find_or_create_by!(name: '洌', kana: 'れつ', company: c)
Brand.find_or_create_by!(name: '日本響', kana: 'にほんひびき', company: c)
c = Company.create_or_find_by!(name: '香坂酒造', kana: 'こうさかしゅぞう', prefecture_code: 6, city: '米沢市', address: '中央7-3-10', tel: '0238-23-3355', fax: '0238-23-3399', website: 'http://www.ko-bai.sakura.ne.jp')
Brand.find_or_create_by!(name: 'マイ・ミニオン', kana: 'まい・みにおん', company: c)
Brand.find_or_create_by!(name: '鷹山', kana: 'ようざん', company: c)
Brand.find_or_create_by!(name: '香梅', kana: 'こうばい', company: c)
c = Company.create_or_find_by!(name: '新藤酒造店', kana: 'しんどうしゅぞうてん', prefecture_code: 6, city: '米沢市', address: '竹井1331', tel: '0238-28-3403', fax: '0238-28-3406', website: 'http://kurouzaemon.com')
Brand.find_or_create_by!(name: '雪国慕情', kana: 'ゆきぐにぼじょう', company: c)
Brand.find_or_create_by!(name: '泉氷艦', kana: 'いずみひょうかん', company: c)
Brand.find_or_create_by!(name: '雅山流', kana: 'がさんりゅう', company: c)
Brand.find_or_create_by!(name: '羽陽富久鶴', kana: 'うようふくつる', company: c)
Brand.find_or_create_by!(name: '千山万水', kana: 'せんざんばんすい', company: c)
Brand.find_or_create_by!(name: '九郎左衛門', kana: 'くろうざえもん', company: c)
Brand.find_or_create_by!(name: '裏・雅山流', kana: 'うら・がさんりゅう', company: c)
c = Company.create_or_find_by!(name: '後藤康太郎酒造店', kana: 'ごとうやすたろうしゅぞうてん', prefecture_code: 6, city: '東置賜郡', address: '高畠町元和田732', tel: '0238-56-3120', fax: '0238-56-3280', website: 'http://www.kin-ran.com')
Brand.find_or_create_by!(name: '桜羽前', kana: 'さくらうぜん', company: c)
Brand.find_or_create_by!(name: '羽陽錦爛', kana: 'うようきんらん', company: c)
c = Company.create_or_find_by!(name: '米鶴酒造', kana: 'よねつるしゅぞう', prefecture_code: 6, city: '東置賜郡', address: '高畠町二井宿1076', tel: '0238-52-1130', fax: '0238-52-3200', website: 'https://yonetsuru.com')
Brand.find_or_create_by!(name: '米鶴', kana: 'よねつる', company: c)
Brand.find_or_create_by!(name: 'マルマス米鶴', kana: 'まるますよねつる', company: c)
Brand.find_or_create_by!(name: 'うきたむ', kana: 'うきたむ', company: c)
Brand.find_or_create_by!(name: 'かっぱ', kana: 'かっぱ', company: c)
c = Company.create_or_find_by!(name: '東の麓酒造', kana: 'あずまのふもとしゅぞう', prefecture_code: 6, city: '南陽市', address: '宮内2557', tel: '0238-47-5111', fax: '0238-47-2013', website: 'https://azumanofumoto.co.jp')
Brand.find_or_create_by!(name: '東の麓', kana: 'あずまのふもと', company: c)
Brand.find_or_create_by!(name: '龍龍龍龍', kana: 'てつ', company: c)
Brand.find_or_create_by!(name: 'つや姫なんどでも', kana: 'つやひめなんどでも', company: c)
Brand.find_or_create_by!(name: '山の形', kana: 'やまのかたち', company: c)
Brand.find_or_create_by!(name: '天弓', kana: 'てんきゅう', company: c)
c = Company.create_or_find_by!(name: '中沖酒造店', kana: 'なかおきしゅぞうてん', prefecture_code: 6, city: '東置賜郡', address: '川西町西大塚1792-3', tel: '0238-42-4116', fax: '0238-42-2615', website: '')
Brand.find_or_create_by!(name: '羽陽一献', kana: 'うよういっこん', company: c)
c = Company.create_or_find_by!(name: '加茂川', kana: 'かもがわ', prefecture_code: 6, city: '西置賜郡', address: '白鷹町鮎貝3258', tel: '0238-85-3151', fax: '0238-85-3062', website: '')
Brand.find_or_create_by!(name: '古時計', kana: 'ふるどけい', company: c)
Brand.find_or_create_by!(name: '瑞露鷹山', kana: 'ずいろようざん', company: c)
Brand.find_or_create_by!(name: '久保桜', kana: 'くぼざくら', company: c)
Brand.find_or_create_by!(name: '日の出加茂川', kana: 'ひのでかもがわ', company: c)
c = Company.create_or_find_by!(name: '東洋酒造', kana: 'とうようしゅぞう', prefecture_code: 6, city: '長井市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '忍ぶ川', kana: 'しのぶかわ', company: c)
Brand.find_or_create_by!(name: '一生幸福', kana: 'いっしょうこうふく', company: c)
Brand.find_or_create_by!(name: '天のつぶ', kana: 'てんのつぶ', company: c)
c = Company.create_or_find_by!(name: '鈴木酒造店 長井蔵', kana: 'すずきしゅぞうてん ながいぐら', prefecture_code: 6, city: '長井市', address: '四ツ谷1-2-21', tel: '0238-88-2224', fax: '0238-88-3503', website: 'http://www.iw-kotobuki.co.jp')
Brand.find_or_create_by!(name: '土耕ん醸', kana: 'どこんじょう', company: c)
Brand.find_or_create_by!(name: '磐城壽', kana: 'いわきことぶき', company: c)
c = Company.create_or_find_by!(name: '寺嶋酒造本舗', kana: 'てらしましゅぞうほんぽ', prefecture_code: 6, city: '長井市', address: '寺泉3496', tel: '0238-84-5388', fax: '0238-84-5389', website: '')
Brand.find_or_create_by!(name: '朝瀧', kana: 'あさたき', company: c)
c = Company.create_or_find_by!(name: 'おきたま五蔵会', kana: 'おきたまごくらかい', prefecture_code: 6, city: '長井市', address: '栄町7-2　中央会館', tel: '0238-84-1671', fax: '0238-84-1780', website: 'http://gokurakai.com')
Brand.find_or_create_by!(name: 'スカイハイ', kana: 'すかいはい', company: c)
c = Company.create_or_find_by!(name: '長沼', kana: 'ながぬま', prefecture_code: 6, city: '長井市', address: '十日町1-1-39', tel: '0238-88-2007', fax: '0238-88-2087', website: 'https://soumura.com')
Brand.find_or_create_by!(name: '誉小桜', kana: 'ほまれこざくら', company: c)
Brand.find_or_create_by!(name: '惣邑', kana: 'そうむら', company: c)
Brand.find_or_create_by!(name: '小桜', kana: 'こざくら', company: c)
Brand.find_or_create_by!(name: '惣右衛門', kana: 'そうえもん', company: c)
c = Company.create_or_find_by!(name: '出羽桜酒造', kana: 'でわざくらしゅぞう', prefecture_code: 6, city: '天童市', address: '一日町1-4-6', tel: '023-653-5121', fax: '023-653-0600', website: 'https://www.dewazakura.co.jp')
Brand.find_or_create_by!(name: '出羽桜', kana: 'でわざくら', company: c)
Brand.find_or_create_by!(name: '郷魂', kana: 'ごうこん', company: c)
c = Company.create_or_find_by!(name: '水戸部酒造', kana: 'みとべしゅぞう', prefecture_code: 6, city: '天童市', address: '原町乙7', tel: '023-653-2131', fax: '023-654-8390', website: 'http://www.mitobesake.com')
Brand.find_or_create_by!(name: '酔芙蓉', kana: 'すいふよう', company: c)
Brand.find_or_create_by!(name: '四方山ばなし', kana: 'よもやまばなし', company: c)
Brand.find_or_create_by!(name: '山形正宗', kana: 'やまがたまさむね', company: c)
c = Company.create_or_find_by!(name: '高木酒造', kana: 'たかぎしゅぞう', prefecture_code: 6, city: '村山市', address: '富並1826', tel: '0237-57-2131', fax: '0237-57-2133', website: '')
Brand.find_or_create_by!(name: '朝日鷹', kana: 'あさひたか', company: c)
Brand.find_or_create_by!(name: '黒縄', kana: 'くろなわ', company: c)
Brand.find_or_create_by!(name: '十四代', kana: 'じゅうよんだい', company: c)
c = Company.create_or_find_by!(name: '最上川酒造', kana: 'もがみがわしゅぞう', prefecture_code: 6, city: '新庄市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '最上川', kana: 'もがみがわ', company: c)
c = Company.create_or_find_by!(name: '小屋酒造', kana: 'こやしゅぞう', prefecture_code: 6, city: '最上郡', address: '大蔵村清水2591', tel: '0233-75-2001', fax: '0233-75-3077', website: 'http://hanauyo.co.jp')
Brand.find_or_create_by!(name: '花羽陽', kana: 'はなうよう', company: c)
Brand.find_or_create_by!(name: '此君', kana: 'このきみ', company: c)
Brand.find_or_create_by!(name: '最上川', kana: 'もがみがわ', company: c)
Brand.find_or_create_by!(name: '絹', kana: 'きぬ', company: c)
c = Company.create_or_find_by!(name: '亀の井酒造', kana: 'かめのいしゅぞう', prefecture_code: 6, city: '鶴岡市', address: '羽黒町戸野福ノ内1', tel: '0235-62-2307', fax: '0235-62-4202', website: '')
Brand.find_or_create_by!(name: 'くどき上手', kana: 'くどきじょうず', company: c)
Brand.find_or_create_by!(name: '藤島', kana: 'ふじしま', company: c)
c = Company.create_or_find_by!(name: '竹の露酒造場', kana: 'たけのつゆしゅぞうじょう', prefecture_code: 6, city: '鶴岡市', address: '羽黒町猪俣新田田屋前133', tel: '0235-62-2209', fax: '0235-62-3306', website: 'http://www.takenotsuyu.com')
Brand.find_or_create_by!(name: '摩耶姫', kana: 'まやひめ', company: c)
Brand.find_or_create_by!(name: '白露垂珠', kana: 'はくろすいしゅ', company: c)
Brand.find_or_create_by!(name: '遊', kana: 'あそび', company: c)
Brand.find_or_create_by!(name: '竹の露', kana: 'たけのつゆ', company: c)
Brand.find_or_create_by!(name: '羽黒山', kana: 'はぐろさん', company: c)
c = Company.create_or_find_by!(name: '奥羽自慢', kana: 'おううじまん', prefecture_code: 6, city: '鶴岡市', address: '上山添字神明前123', tel: '0235-57-2095', fax: '0235-57-2011', website: 'http://oujiman.jp')
Brand.find_or_create_by!(name: '吾有事', kana: 'わがうじ', company: c)
Brand.find_or_create_by!(name: '奥羽自慢', kana: 'おううじまん', company: c)
c = Company.create_or_find_by!(name: '冨士酒造', kana: 'ふじしゅぞう', prefecture_code: 6, city: '鶴岡市', address: '大山3-32-48', tel: '0235-33-3200', fax: '0235-33-0477', website: 'http://www.e-sakenom.com')
Brand.find_or_create_by!(name: '虎穴', kana: 'こけつ', company: c)
Brand.find_or_create_by!(name: '有加藤', kana: 'ありかとう', company: c)
Brand.find_or_create_by!(name: '栄光冨士', kana: 'えいこうふじ', company: c)
c = Company.create_or_find_by!(name: '加藤嘉八郎酒造', kana: 'かとうかはちろうしゅぞう', prefecture_code: 6, city: '鶴岡市', address: '大山3-1-38', tel: '0235-33-2008', fax: '0235-33-0880', website: 'http://katokahachiro.web.fc2.com')
Brand.find_or_create_by!(name: '大山', kana: 'おおやま', company: c)
c = Company.create_or_find_by!(name: '渡會本店', kana: 'わたらいほんてん', prefecture_code: 6, city: '鶴岡市', address: '大山2-2-8', tel: '0235-33-3262', fax: '0235-33-3368', website: 'http://www.dewanoyuki.com')
Brand.find_or_create_by!(name: 'ORBIA LUNA', kana: 'オルヴィア ルナ', company: c)
Brand.find_or_create_by!(name: '出羽ノ雪', kana: 'でわのゆき', company: c)
Brand.find_or_create_by!(name: '和田来', kana: 'わたらい', company: c)
Brand.find_or_create_by!(name: '乙女の舞', kana: 'おとめのまい', company: c)
Brand.find_or_create_by!(name: 'イ号 彌太右衛門', kana: 'やたえもん', company: c)
c = Company.create_or_find_by!(name: '羽根田酒造', kana: 'はねだしゅぞう', prefecture_code: 6, city: '鶴岡市', address: '大山2-1-15', tel: '0235-33-2058', fax: '0235-33-1221', website: '')
Brand.find_or_create_by!(name: '羽前白梅', kana: 'うぜんしらうめ', company: c)
c = Company.create_or_find_by!(name: '酒田酒造', kana: 'さかたしゅぞう', prefecture_code: 6, city: '酒田市', address: '日吉町2-3-25', tel: '0234-22-1541', fax: '0234-22-1542', website: '')
Brand.find_or_create_by!(name: '上喜元', kana: 'じょうきげん', company: c)
c = Company.create_or_find_by!(name: '菊勇', kana: 'きくいさみ', prefecture_code: 6, city: '酒田市', address: '黒森葭葉山650', tel: '0234-92-2323', fax: '0234-92-2485', website: '')
Brand.find_or_create_by!(name: '菊勇', kana: 'きくいさみ', company: c)
Brand.find_or_create_by!(name: '三十六人衆', kana: 'さんじゅうろくにんしゅう', company: c)
c = Company.create_or_find_by!(name: 'オードヴィ庄内', kana: 'オードヴィしょうない', prefecture_code: 6, city: '酒田市', address: '浜中乙123', tel: '0234-92-2046', fax: '0234-92-2045', website: 'http://kiyoizumigawa.com')
Brand.find_or_create_by!(name: 'ORBIA GAIA', kana: 'オルヴィア ガイア', company: c)
Brand.find_or_create_by!(name: '清泉川', kana: 'きよいずみがわ', company: c)
Brand.find_or_create_by!(name: 'FONIA SORRA', kana: 'フォニア ソラ', company: c)
Brand.find_or_create_by!(name: '穂のかおり', kana: 'ほのかおり', company: c)
Brand.find_or_create_by!(name: '占飲', kana: 'しめのみ', company: c)
c = Company.create_or_find_by!(name: '東北銘醸', kana: 'とうほくめいじょう', prefecture_code: 6, city: '酒田市', address: '十里塚村東山125-3', tel: '0234-31-1515', fax: '0234-31-5588', website: 'http://www.hatsumago.co.jp')
Brand.find_or_create_by!(name: '初孫', kana: 'はつまご', company: c)
Brand.find_or_create_by!(name: '摩耶山', kana: 'まやさん', company: c)
Brand.find_or_create_by!(name: '砂潟', kana: 'さかた', company: c)
c = Company.create_or_find_by!(name: '嵐山酒造', kana: 'あらしやましゅぞう', prefecture_code: 6, city: '東置賜郡', address: '川西町上小松3182', tel: '0238-42-3040', fax: '0238-42-2570', website: '')
Brand.find_or_create_by!(name: '花娘', kana: 'はなむすめ', company: c)
Brand.find_or_create_by!(name: '白銀蔵王', kana: 'はくぎんざおう', company: c)
c = Company.create_or_find_by!(name: '樽平酒造', kana: 'たるへいしゅぞう', prefecture_code: 6, city: '東置賜郡', address: '川西町中小松2886', tel: '0238-42-3101', fax: '0238-42-3104', website: 'http://www.taruhei.co.jp')
Brand.find_or_create_by!(name: '樽平', kana: 'たるへい', company: c)
Brand.find_or_create_by!(name: '雪むかえ', kana: 'ゆきむかえ', company: c)
Brand.find_or_create_by!(name: '住吉', kana: 'すみよし', company: c)
c = Company.create_or_find_by!(name: '福牡丹酒造', kana: 'ふくぼたんしゅぞう', prefecture_code: 6, city: '東置賜郡', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '福牡丹', kana: 'ふくぼたん', company: c)
c = Company.create_or_find_by!(name: '若乃井酒造', kana: 'わかのいしゅぞう', prefecture_code: 6, city: '西置賜郡', address: '飯豊町中947-3', tel: '0238-72-2020', fax: '0238-72-3471', website: 'http://www.wakanoi.jp')
Brand.find_or_create_by!(name: '若乃井', kana: 'わかのい', company: c)
Brand.find_or_create_by!(name: '飯豊山', kana: 'いいでさん', company: c)
c = Company.create_or_find_by!(name: '桜川酒造', kana: 'さくらがわしゅぞうてん', prefecture_code: 6, city: '西置賜郡', address: '小国町小国小坂町213', tel: '0238-62-2011', fax: '0238-62-2019', website: '')
Brand.find_or_create_by!(name: '小国桜川', kana: 'おぐにさくらがわ', company: c)
c = Company.create_or_find_by!(name: '後藤酒造店', kana: 'ごとうしゅぞうてん', prefecture_code: 6, city: '東置賜郡', address: '高畠町糠野目1462', tel: '0238-57-3136', fax: '0238-57-3282', website: 'http://www.benten-goto.com')
Brand.find_or_create_by!(name: '酒中楽康', kana: 'しゅちゅうらっこう', company: c)
Brand.find_or_create_by!(name: '辯天', kana: 'べんてん', company: c)
c = Company.create_or_find_by!(name: '和田酒造', kana: 'わだしゅぞう', prefecture_code: 6, city: '西村山郡', address: '河北町谷地甲17', tel: '0237-72-3105', fax: '0237-72-3598', website: 'http://www.hinanet.ne.jp/~aratama')
Brand.find_or_create_by!(name: 'Salute 冴', kana: 'さるーて さえ', company: c)
Brand.find_or_create_by!(name: 'あら玉', kana: 'あらたま', company: c)
c = Company.create_or_find_by!(name: '朝日川酒造', kana: 'あさひかわしゅぞう', prefecture_code: 6, city: '西村山郡', address: '河北町谷地乙93', tel: '0237-72-2022', fax: '0237-72-7197', website: 'http://www.hinanet.ne.jp/~asahikawa')
Brand.find_or_create_by!(name: '朝日川', kana: 'あさひかわ', company: c)
Brand.find_or_create_by!(name: '山吹極', kana: 'やまぶき', company: c)
c = Company.create_or_find_by!(name: '六歌仙', kana: 'ろっかせん', prefecture_code: 6, city: '東根市', address: '温泉町3-17-7', tel: '0237-42-2777', fax: '0237-43-6074', website: 'http://www.yamagata-rokkasen.co.jp')
Brand.find_or_create_by!(name: '六歌仙', kana: 'ろっかせん', company: c)
Brand.find_or_create_by!(name: '手間暇', kana: 'てまひま', company: c)
Brand.find_or_create_by!(name: 'ひととき', kana: 'ひととき', company: c)
Brand.find_or_create_by!(name: '山法師', kana: 'やまほうし', company: c)
Brand.find_or_create_by!(name: '花ちよ', kana: 'はなちよ', company: c)
c = Company.create_or_find_by!(name: '佐藤酒造店', kana: 'さとうしゅぞうてん', prefecture_code: 6, city: '最上郡', address: '最上町大堀1026', tel: '0233-42-2403', fax: '0233-42-2303', website: '')
Brand.find_or_create_by!(name: '最上の夢', kana: 'もがみのゆめ', company: c)
c = Company.create_or_find_by!(name: '楯の川酒造', kana: 'たてのかわしゅぞう', prefecture_code: 6, city: '酒田市', address: '山楯清水田27', tel: '0234-52-2323', fax: '0234-52-2324', website: 'https://www.tatenokawa.com')
Brand.find_or_create_by!(name: '楯野川', kana: 'たてのかわ', company: c)
Brand.find_or_create_by!(name: 'Nature-H', kana: 'ナチュルフ', company: c)
Brand.find_or_create_by!(name: 'Shield', kana: 'シールド', company: c)
Brand.find_or_create_by!(name: '百光', kana: 'びゃっこう', company: c)
Brand.find_or_create_by!(name: '無我', kana: 'むが', company: c)
c = Company.create_or_find_by!(name: '松山酒造', kana: 'まつやましゅぞう', prefecture_code: 6, city: '酒田市', address: '荒町17', tel: '0234-62-2003', fax: '0234-62-2559', website: 'http://fujiyashop.pripri-online.com')
Brand.find_or_create_by!(name: '天盃富士', kana: 'てんぱいふじ', company: c)
Brand.find_or_create_by!(name: '松嶺の富士', kana: 'まつみねのふじ', company: c)
c = Company.create_or_find_by!(name: '佐藤佐治右衛門', kana: 'さとうさじうえもん', prefecture_code: 6, city: '東田川郡', address: '庄内町余目字町255', tel: '0234-42-3013', fax: '0234-42-3522', website: '')
Brand.find_or_create_by!(name: 'やまと桜', kana: 'やまとざくら', company: c)
c = Company.create_or_find_by!(name: '鯉川酒造', kana: 'こいかわしゅぞう', prefecture_code: 6, city: '東田川郡', address: '庄内町余目興野42', tel: '0234-43-2005', fax: '0234-43-2007', website: '')
Brand.find_or_create_by!(name: '梅川', kana: 'うめかわ', company: c)
Brand.find_or_create_by!(name: '侍士の門', kana: 'さむらいのもん', company: c)
Brand.find_or_create_by!(name: '亀治好日', kana: 'かめじこうじつ', company: c)
Brand.find_or_create_by!(name: '庄内の風', kana: 'しょうないのかぜ', company: c)
Brand.find_or_create_by!(name: '別嬪', kana: 'べっぴん', company: c)
Brand.find_or_create_by!(name: '恋の川', kana: 'こいのかわ', company: c)
Brand.find_or_create_by!(name: '鯉川', kana: 'こいかわ', company: c)
Brand.find_or_create_by!(name: '白凛', kana: 'はくりん', company: c)
Brand.find_or_create_by!(name: '鯉ヶ龍', kana: 'こいがりゅう', company: c)
Brand.find_or_create_by!(name: '余目', kana: 'あまるめ', company: c)
c = Company.create_or_find_by!(name: '麓井酒造', kana: 'ふもといしゅぞう', prefecture_code: 6, city: '酒田市', address: '麓字横道32', tel: '0234-64-2002', fax: '0234-64-2132', website: '')
Brand.find_or_create_by!(name: '麓井', kana: 'ふもとい', company: c)
c = Company.create_or_find_by!(name: '杉勇蕨岡酒造場', kana: 'すぎいさみわらびおかしゅぞうじょう', prefecture_code: 6, city: '飽海郡', address: '遊佐町上蕨岡御備田47-1', tel: '0234-72-2234', fax: '0234-72-2234', website: '')
Brand.find_or_create_by!(name: '遊佐来', kana: 'ゆざこい', company: c)
Brand.find_or_create_by!(name: '嵐童', kana: 'らんどう', company: c)
Brand.find_or_create_by!(name: '鳥海探酔物語', kana: 'ちょうかいたんすいものがたり', company: c)
Brand.find_or_create_by!(name: '杉勇', kana: 'すぎいさみ', company: c)
Brand.find_or_create_by!(name: 'はなわらび', kana: 'はなわらび', company: c)
c = Company.create_or_find_by!(name: '高橋酒造店', kana: 'たかはししゅぞうてん', prefecture_code: 6, city: '飽海郡', address: '遊佐町吹浦一本木57', tel: '0234-77-2005', fax: '0234-77-2168', website: 'http://www.touhokuizumi.co.jp')
Brand.find_or_create_by!(name: '東北泉', kana: 'とうほくいずみ', company: c)
