c = Company.create_or_find_by!(name: '山崎酒造', kana: 'やまざきしゅぞう', prefecture_code: 10, city: '太田市', address: '新田木崎町966', tel: '0276-56-1241', fax: '0276-56-3360', website: 'http://www.yamazaki-shuzo.com')
Brand.find_or_create_by!(name: '日本譽', kana: 'にほんほまれ', company: c)
Brand.find_or_create_by!(name: '誠の心', kana: 'まことのこころ', company: c)
Brand.find_or_create_by!(name: '太平記の里', kana: 'たいへいきのさと', company: c)
c = Company.create_or_find_by!(name: '山川酒造', kana: 'やまかわしゅぞう', prefecture_code: 10, city: '邑楽郡', address: '千代田町赤岩185-3', tel: '0276-86-2182', fax: '0276-86-2182', website: '')
Brand.find_or_create_by!(name: '光東', kana: 'こうとう', company: c)
Brand.find_or_create_by!(name: '利根川育ち', kana: 'とねがわそだち', company: c)
c = Company.create_or_find_by!(name: '岡村合名', kana: 'おかむらごうめい', prefecture_code: 10, city: '高崎市', address: '台町5', tel: '027-322-4137', fax: '027-322-4137', website: '')
Brand.find_or_create_by!(name: '泉末広', kana: 'いずみすえひろ', company: c)
Brand.find_or_create_by!(name: '観音桜', kana: 'かんのんさくら', company: c)
c = Company.create_or_find_by!(name: '美峰酒類', kana: 'みほうしゅるい', prefecture_code: 10, city: '高崎市', address: '歌川町1', tel: '027-322-2155', fax: '027-322-0084', website: 'http://www.mihoshurui.co.jp')
Brand.find_or_create_by!(name: '朝日桜', kana: 'あさひざくら', company: c)
Brand.find_or_create_by!(name: '蔵自慢', kana: 'くらじまん', company: c)
c = Company.create_or_find_by!(name: '町田酒造店', kana: 'まちだしゅぞうてん', prefecture_code: 10, city: '佐波郡', address: '玉村町下新田619', tel: '0270-65-2050', fax: '0270-65-2886', website: '')
Brand.find_or_create_by!(name: '太平人', kana: 'たいへいじん', company: c)
c = Company.create_or_find_by!(name: '井田酒造', kana: 'いだしゅぞう', prefecture_code: 10, city: '佐波郡', address: '玉村町上新田1626', tel: '0270-65-2007', fax: '0270-65-8106', website: '')
Brand.find_or_create_by!(name: 'ふじ泉', kana: 'ふじいずみ', company: c)
c = Company.create_or_find_by!(name: '藤﨑摠兵衛商店 鬼石支店', kana: 'ふじさきそうべえしょうてん おにししてん', prefecture_code: 10, city: '藤岡市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '鬼面山', kana: 'きめんざん', company: c)
Brand.find_or_create_by!(name: '寒桜', kana: 'かんざくら', company: c)
c = Company.create_or_find_by!(name: '聖徳銘醸', kana: 'せいとくめいじょう', prefecture_code: 10, city: '甘楽郡', address: '甘楽町白倉686-1', tel: '0274-74-4111', fax: '0274-74-6325', website: '')
Brand.find_or_create_by!(name: '妙義山', kana: 'みょうぎさん', company: c)
Brand.find_or_create_by!(name: '蔵群', kana: 'くらむれ', company: c)
Brand.find_or_create_by!(name: '城下町小幡', kana: 'じょうかまちおばた', company: c)
Brand.find_or_create_by!(name: '聖徳', kana: 'せいとく', company: c)
c = Company.create_or_find_by!(name: '牧野酒造', kana: 'まきのしゅぞう', prefecture_code: 10, city: '高崎市', address: '倉渕町権田2625-1', tel: '027-378-2011', fax: '027-378-3954', website: 'https://www.makino-sake.co.jp')
Brand.find_or_create_by!(name: '大盃', kana: 'おおさかずき', company: c)
Brand.find_or_create_by!(name: '榛名山', kana: 'はるなさん', company: c)
Brand.find_or_create_by!(name: '夢二ものがたり', kana: 'ゆめじものがたり', company: c)
Brand.find_or_create_by!(name: '高崎', kana: 'たかさき', company: c)
Brand.find_or_create_by!(name: '馥露酣', kana: 'ふくろかん', company: c)
c = Company.create_or_find_by!(name: '柴崎酒造', kana: 'しばさきしゅぞう', prefecture_code: 10, city: '北群馬郡', address: '吉岡町下野田649-1', tel: '0279-55-1141', fax: '0279-54-0601', website: '')
Brand.find_or_create_by!(name: '船尾瀧', kana: 'ふなおたき', company: c)
c = Company.create_or_find_by!(name: '伴内酒造店', kana: 'ばんないしゅぞうてん', prefecture_code: 10, city: '前橋市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '聖人', kana: 'せいじん', company: c)
c = Company.create_or_find_by!(name: '柳澤酒造', kana: 'やなぎさわしゅぞう', prefecture_code: 10, city: '前橋市', address: '粕川町深津104-2', tel: '027-285-2005', fax: '027-285-5558', website: 'http://www.katsuragawa-sake.co.jp')
Brand.find_or_create_by!(name: '勝楽雅和', kana: 'かつらがわ', company: c)
Brand.find_or_create_by!(name: '絶滅危惧酒', kana: 'ぜつめつきぐしゅ', company: c)
Brand.find_or_create_by!(name: '結人', kana: 'むすびと', company: c)
Brand.find_or_create_by!(name: '桂川', kana: 'かつらがわ', company: c)
c = Company.create_or_find_by!(name: '七ツ星醸造', kana: 'ななつぼしじょうぞう', prefecture_code: 10, city: '前橋市', address: '大胡町12', tel: '027-283-2011', fax: '027-283-1273', website: 'http://www.kiminomatsu.co.jp')
Brand.find_or_create_by!(name: '暴れ獅子', kana: 'あばれじし', company: c)
Brand.find_or_create_by!(name: '君乃松', kana: 'きみのまつ', company: c)
c = Company.create_or_find_by!(name: '太刀川酒造', kana: 'たちかわしゅぞう', prefecture_code: 10, city: '太田市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '利根鶴', kana: 'とねつる', company: c)
c = Company.create_or_find_by!(name: '島岡酒造', kana: 'しまおかしゅぞう', prefecture_code: 10, city: '太田市', address: '由良町375-2', tel: '0276-31-2432', fax: '0276-31-7715', website: 'https://shimaokasyuzo.com')
Brand.find_or_create_by!(name: '群馬泉', kana: 'ぐんまいずみ', company: c)
c = Company.create_or_find_by!(name: '今井酒造店', kana: 'いまいしゅぞうてん', prefecture_code: 10, city: '太田市', address: '鳥山中町746-2', tel: '0276-22-2680', fax: '0276-22-2687', website: 'http://www.nihonsyu.org')
Brand.find_or_create_by!(name: 'むつらぼし', kana: 'むつらぼし', company: c)
Brand.find_or_create_by!(name: '神龍', kana: 'しんりゅう', company: c)
Brand.find_or_create_by!(name: '風まかせ', kana: 'かぜまかせ', company: c)
Brand.find_or_create_by!(name: '新田山', kana: 'にいたやま', company: c)
c = Company.create_or_find_by!(name: '分福酒造', kana: 'ぶんぶくしゅぞう', prefecture_code: 10, city: '館林市', address: '仲町3-15', tel: '0276-72-0017', fax: '0276-75-1977', website: 'http://www.bunbuku.net')
Brand.find_or_create_by!(name: '男一心', kana: 'おとこいっしん', company: c)
Brand.find_or_create_by!(name: '分福', kana: 'ぶんぶく', company: c)
c = Company.create_or_find_by!(name: '龍神酒造', kana: 'りゅうじんしゅぞう', prefecture_code: 10, city: '館林市', address: '西本町7-13', tel: '0276-72-3711', fax: '0276-72-3968', website: 'http://www.ryujin.jp')
Brand.find_or_create_by!(name: '尾瀬の雪どけ', kana: 'おぜのゆきどけ', company: c)
Brand.find_or_create_by!(name: '龍神', kana: 'りゅうじん', company: c)
c = Company.create_or_find_by!(name: '清水屋酒造', kana: 'しみずやしゅぞう', prefecture_code: 10, city: '館林市', address: '台宿町3-10', tel: '0276-74-0269', fax: '0276-74-1303', website: 'https://sakaemasu.com')
Brand.find_or_create_by!(name: 'KIYOMIZU', kana: 'きよみず', company: c)
Brand.find_or_create_by!(name: '榮万寿', kana: 'さかえます', company: c)
c = Company.create_or_find_by!(name: '松屋酒造', kana: 'まつやしゅぞう', prefecture_code: 10, city: '藤岡市', address: '藤岡180', tel: '0274-22-0022', fax: '0274-24-0544', website: 'https://www.tousenkura.jp')
Brand.find_or_create_by!(name: '當選', kana: 'とうせん', company: c)
Brand.find_or_create_by!(name: '平井城', kana: 'ひらいじょう', company: c)
Brand.find_or_create_by!(name: 'ねむり酒', kana: 'ねむりざけ', company: c)
Brand.find_or_create_by!(name: '流輝', kana: 'るか', company: c)
c = Company.create_or_find_by!(name: '田島酒造店', kana: 'たじましゅぞうてん', prefecture_code: 10, city: '藤岡市', address: '神田899', tel: '0274-22-0808', fax: '0274-23-0251', website: '')
Brand.find_or_create_by!(name: '三波石', kana: 'さんばせき', company: c)
c = Company.create_or_find_by!(name: '高井', kana: 'たかい', prefecture_code: 10, city: '藤岡市', address: '鮎川138', tel: '0274-24-0011', fax: '0274-24-3118', website: '')
Brand.find_or_create_by!(name: '巌', kana: 'いわお', company: c)
Brand.find_or_create_by!(name: '上州の寒梅', kana: 'じょうしゅうのかんばい', company: c)
Brand.find_or_create_by!(name: '十代目作右衛門', kana: 'じゅうだいめさくえもん', company: c)
c = Company.create_or_find_by!(name: '奥村酒造', kana: 'おくむらしゅぞう', prefecture_code: 10, city: 'みどり市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '福榮', kana: 'ふくえい', company: c)
Brand.find_or_create_by!(name: '上州っ子', kana: 'じょうしゅうっこ', company: c)
Brand.find_or_create_by!(name: '起龍', kana: 'きりゅう', company: c)
c = Company.create_or_find_by!(name: '近藤酒造', kana: 'こんどうしゅぞう', prefecture_code: 10, city: 'みどり市', address: '大間々町大間々1002', tel: '0277-72-2221', fax: '0277-73-1603', website: 'http://www.akagisan.com')
Brand.find_or_create_by!(name: '赤城山', kana: 'あかぎさん', company: c)
c = Company.create_or_find_by!(name: '聖酒造', kana: 'ひじりしゅぞう', prefecture_code: 10, city: '渋川市', address: '北橘町下箱田380', tel: '0279-52-3911', fax: '0279-52-3900', website: 'http://www.hijiri-sake.co.jp')
Brand.find_or_create_by!(name: '木曽川', kana: 'きそがわ', company: c)
Brand.find_or_create_by!(name: '関東の華', kana: 'かんとうのはな', company: c)
Brand.find_or_create_by!(name: '駒正宗', kana: 'こままさむね', company: c)
Brand.find_or_create_by!(name: '聖', kana: 'ひじり', company: c)
Brand.find_or_create_by!(name: 'からっ風', kana: 'からっかぜ', company: c)
Brand.find_or_create_by!(name: '入駒', kana: 'いりこま', company: c)
Brand.find_or_create_by!(name: '酒屋 傳兵衛', kana: 'さかや でんべえ', company: c)
c = Company.create_or_find_by!(name: '貴娘酒造', kana: 'きむすめしゅぞう', prefecture_code: 10, city: '吾妻郡', address: '中之条町大塚1768-2', tel: '0279-75-3146', fax: '0279-75-3144', website: '')
Brand.find_or_create_by!(name: '風の詩', kana: 'かぜのうた', company: c)
Brand.find_or_create_by!(name: '貴娘', kana: 'きむすめ', company: c)
Brand.find_or_create_by!(name: '牧水の詩', kana: 'ぼくすいのうた', company: c)
Brand.find_or_create_by!(name: '咲耶美', kana: 'さくやび', company: c)
c = Company.create_or_find_by!(name: '浅間酒造', kana: 'あさましゅぞう', prefecture_code: 10, city: '吾妻郡', address: '長野原町長野原30-8', tel: '0279-82-2045', fax: '0279-82-3722', website: 'https://asama-sakagura.co.jp')
Brand.find_or_create_by!(name: '草津節', kana: 'くさつぶし', company: c)
Brand.find_or_create_by!(name: '浅間山', kana: 'あさまやま', company: c)
Brand.find_or_create_by!(name: '秘幻', kana: 'ひげん', company: c)
Brand.find_or_create_by!(name: 'つま恋美人', kana: 'つまごいびじん', company: c)
c = Company.create_or_find_by!(name: '永井本家', kana: 'ながいほんけ', prefecture_code: 10, city: '沼田市', address: '下発知町703', tel: '0278-23-9118', fax: '0278-23-9437', website: 'http://www.nagaihonke.co.jp')
Brand.find_or_create_by!(name: '尾瀬のあわ雪', kana: 'おぜのあわゆき', company: c)
Brand.find_or_create_by!(name: '利根錦', kana: 'とねにしき', company: c)
c = Company.create_or_find_by!(name: '土田酒造', kana: 'つちだしゅぞう', prefecture_code: 10, city: '利根郡', address: '川場村川場湯原2691', tel: '0278-52-3511', fax: '0278-52-3513', website: 'https://tsuchidasake.jp')
Brand.find_or_create_by!(name: '誉国光', kana: 'ほまれこっこう', company: c)
Brand.find_or_create_by!(name: '土田', kana: 'つちだ', company: c)
c = Company.create_or_find_by!(name: '永井酒造', kana: 'ながいしゅぞう', prefecture_code: 10, city: '利根郡', address: '川場村門前713', tel: '0278-52-2311', fax: '0278-52-2314', website: 'http://www.nagai-sake.co.jp')
Brand.find_or_create_by!(name: '水芭蕉', kana: 'みずばしょう', company: c)
Brand.find_or_create_by!(name: '谷川岳', kana: 'たにがわだけ', company: c)
c = Company.create_or_find_by!(name: '大利根酒造', kana: 'おおとねしゅぞう', prefecture_code: 10, city: '沼田市', address: '白沢町高平1306-2', tel: '0278-53-2334', fax: '0278-53-2335', website: 'http://www.sadaijin.co.jp')
Brand.find_or_create_by!(name: '花一匁', kana: 'はないちもんめ', company: c)
Brand.find_or_create_by!(name: '沼田城', kana: 'ぬまたじょう', company: c)
Brand.find_or_create_by!(name: '左大臣', kana: 'さだいじん', company: c)
c = Company.create_or_find_by!(name: '森本酒造', kana: 'もりもとしゅぞう', prefecture_code: 10, city: '前橋市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '赤城の寒梅', kana: 'あかぎのかんばい', company: c)
Brand.find_or_create_by!(name: '黒松正泉', kana: 'くろまつまさいずみ', company: c)
Brand.find_or_create_by!(name: '自然酒', kana: 'しぜんしゅ', company: c)
c = Company.create_or_find_by!(name: '町田酒造店', kana: 'まちだしゅぞうてん', prefecture_code: 10, city: '前橋市', address: '駒形町65', tel: '027-266-0052', fax: '027-266-0779', website: 'https://www.seiryo-sake.co.jp')
Brand.find_or_create_by!(name: '清嘹', kana: 'せいりょう', company: c)
Brand.find_or_create_by!(name: '町田酒造', kana: 'まちだしゅぞう', company: c)
