c = Company.create_or_find_by!(name: '武内酒造店', kana: 'たけうちしゅぞうてん', prefecture_code: 17, city: '金沢市', address: '御所町イ22', tel: '076-252-5476', fax: '076-251-5068', website: '')
Brand.find_or_create_by!(name: '御所泉', kana: 'ごしょいずみ', company: c)
c = Company.create_or_find_by!(name: 'やちや酒造', kana: 'やちやしゅぞう', prefecture_code: 17, city: '金沢市', address: '大樋町8-32', tel: '076-252-7077', fax: '076-252-7449', website: 'http://www.yachiya-sake.co.jp')
Brand.find_or_create_by!(name: '加賀鶴', kana: 'かがつる', company: c)
c = Company.create_or_find_by!(name: '中村酒造', kana: 'なかむらしゅぞう', prefecture_code: 17, city: '金沢市', address: '長土塀3-2-15', tel: '076-248-2435', fax: '076-248-2436', website: 'https://nakamura-shuzou.co.jp')
Brand.find_or_create_by!(name: '加賀雪梅', kana: 'かがせつばい', company: c)
Brand.find_or_create_by!(name: 'ルネサンス金沢', kana: 'るねさんすかなざわ', company: c)
Brand.find_or_create_by!(name: '加賀太鼓', kana: 'かがだいこ', company: c)
Brand.find_or_create_by!(name: 'AKIRA', kana: 'あきら', company: c)
Brand.find_or_create_by!(name: 'すっぽんぽん', kana: 'すっぽんぽん', company: c)
Brand.find_or_create_by!(name: '客人', kana: 'まれびと', company: c)
Brand.find_or_create_by!(name: '日榮', kana: 'にちえい', company: c)
Brand.find_or_create_by!(name: 'アランデュカス', kana: 'あらんでゅかす', company: c)
Brand.find_or_create_by!(name: '金澤中村屋', kana: 'かなざわなかむらや', company: c)
c = Company.create_or_find_by!(name: '小堀酒造店', kana: 'こぼりしゅぞうてん', prefecture_code: 17, city: '白山市', address: '鶴来本町1丁目ワ47番地', tel: '0761-93-1171', fax: '0761-93-3725', website: 'http://www.manzairaku.co.jp')
Brand.find_or_create_by!(name: '萬歳楽', kana: 'まんざいらく', company: c)
Brand.find_or_create_by!(name: '白山', kana: 'はくさん', company: c)
Brand.find_or_create_by!(name: '石川門', kana: 'いしかわもん', company: c)
Brand.find_or_create_by!(name: '獅子吼', kana: 'ししく', company: c)
c = Company.create_or_find_by!(name: '菊姫', kana: 'きくひめ', prefecture_code: 17, city: '白山市', address: '鶴来新町タ8', tel: '076-272-1234', fax: '076-273-1222', website: 'https://www.kikuhime.co.jp')
Brand.find_or_create_by!(name: '菊姫', kana: 'きくひめ', company: c)
c = Company.create_or_find_by!(name: '福光屋', kana: 'ふくみつや', prefecture_code: 17, city: '金沢市', address: '石引2-8-3', tel: '076-223-1161', fax: '076-222-3769', website: 'http://www.fukumitsuya.co.jp')
Brand.find_or_create_by!(name: '百々登勢', kana: 'ももとせ', company: c)
Brand.find_or_create_by!(name: '禱と稔', kana: 'いのりとみのり', company: c)
Brand.find_or_create_by!(name: '金澤', kana: 'かなざわ', company: c)
Brand.find_or_create_by!(name: '加賀鳶', kana: 'かがとび', company: c)
Brand.find_or_create_by!(name: '初心', kana: 'はつごころ', company: c)
Brand.find_or_create_by!(name: 'そして伝説へ…', kana: 'そしてでんせつへ…', company: c)
Brand.find_or_create_by!(name: '加賀纏', kana: 'かがまとい', company: c)
Brand.find_or_create_by!(name: '福正宗', kana: 'ふくまさむね', company: c)
Brand.find_or_create_by!(name: '酒炭酸', kana: 'さけたんさん', company: c)
Brand.find_or_create_by!(name: '黒帯', kana: 'くろおび', company: c)
Brand.find_or_create_by!(name: '瑞秀', kana: 'みずほ', company: c)
Brand.find_or_create_by!(name: '風よ水よ人よ', kana: 'かぜよみずよひとよ', company: c)
Brand.find_or_create_by!(name: '鏡花', kana: 'きょうか', company: c)
c = Company.create_or_find_by!(name: '松浦酒造', kana: 'まつうらしゅぞう', prefecture_code: 17, city: '加賀市', address: '山中温泉冨士見町オ50', tel: '0761-78-1125', fax: '0761-78-1126', website: 'https://shishinosato.com')
Brand.find_or_create_by!(name: '獅子の里', kana: 'ししのさと', company: c)
c = Company.create_or_find_by!(name: '橋本酒造', kana: 'はしもとしゅぞう', prefecture_code: 17, city: '加賀市', address: '動橋町イ184', tel: '0761-74-0602', fax: '0761-74-0603', website: 'https://judaime.com')
Brand.find_or_create_by!(name: '十代目', kana: 'じゅうだいめ', company: c)
Brand.find_or_create_by!(name: '大日盛', kana: 'だいにちざかり', company: c)
Brand.find_or_create_by!(name: '富樫の仁', kana: 'とがしのじん', company: c)
c = Company.create_or_find_by!(name: '鹿野酒造', kana: 'かのしゅぞう', prefecture_code: 17, city: '加賀市', address: '八日市町イ6', tel: '0761-74-1551', fax: '0761-74-6120', website: 'https://www.jokigen.co.jp')
Brand.find_or_create_by!(name: '益荒男', kana: 'ますらお', company: c)
Brand.find_or_create_by!(name: '常きげん', kana: 'じょうきげん', company: c)
c = Company.create_or_find_by!(name: '東酒造', kana: 'ひがししゅぞう', prefecture_code: 17, city: '小松市', address: '野田町丁35', tel: '0761-22-2301', fax: '0761-22-2300', website: 'http://www.sake-sinsen.co.jp')
Brand.find_or_create_by!(name: '神泉', kana: 'しんせん', company: c)
c = Company.create_or_find_by!(name: '農口尚彦研究所', kana: 'のぐちなおひこけんきゅうしょ', prefecture_code: 17, city: '小松市', address: '観音下町ワ1番1', tel: '', fax: '', website: 'https://noguchi-naohiko.co.jp')
Brand.find_or_create_by!(name: '農口尚彦研究所', kana: 'のぐちなおひこけんきゅうしょ', company: c)
c = Company.create_or_find_by!(name: '西出酒造', kana: 'にしでしゅぞう', prefecture_code: 17, city: '小松市', address: '下粟津町ろ24', tel: '0761-44-8188', fax: '0761-44-4521', website: 'https://nishidesake.com')
Brand.find_or_create_by!(name: '春心', kana: 'はるごころ', company: c)
Brand.find_or_create_by!(name: '金紋', kana: 'きんもん', company: c)
Brand.find_or_create_by!(name: '裕恒', kana: 'ひろひさ', company: c)
Brand.find_or_create_by!(name: 'シラヤマフウロ', kana: 'しらやまふうろ', company: c)
c = Company.create_or_find_by!(name: '加越', kana: 'かえつ', prefecture_code: 17, city: '小松市', address: '今江町9-605', tel: '0761-22-5321', fax: '0761-23-1444', website: 'https://www.kanpaku.co.jp')
Brand.find_or_create_by!(name: '加賀ノ月', kana: 'かがのつき', company: c)
Brand.find_or_create_by!(name: 'こっそり', kana: 'こっそり', company: c)
Brand.find_or_create_by!(name: '関白', kana: 'かんぱく', company: c)
Brand.find_or_create_by!(name: '酒峰加越', kana: 'しゅほうかえつ', company: c)
c = Company.create_or_find_by!(name: '手塚酒造場', kana: 'てづかしゅぞうじょう', prefecture_code: 17, city: '小松市', address: '串町庚7', tel: '0761-44-1200', fax: '0761-44-2342', website: '')
Brand.find_or_create_by!(name: '菊鶴', kana: 'きくつる', company: c)
Brand.find_or_create_by!(name: '御幸誉', kana: 'みゆきのほまれ', company: c)
c = Company.create_or_find_by!(name: '農口酒造', kana: 'のぐちしゅぞう', prefecture_code: 17, city: '能美市', address: '末寺町イ42', tel: '0761-57-0021', fax: '0761-57-0106', website: 'http://noguchishuzo.jp')
Brand.find_or_create_by!(name: '農口', kana: 'のぐち', company: c)
Brand.find_or_create_by!(name: '弁慶', kana: 'べんけい', company: c)
Brand.find_or_create_by!(name: '勧進帳', kana: 'かんじんちょう', company: c)
c = Company.create_or_find_by!(name: '宮本酒造店', kana: 'みやもとしゅぞうてん', prefecture_code: 17, city: '能美市', address: '宮竹町イ74', tel: '0761-51-3333', fax: '0761-51-5355', website: 'http://www.mujou.co.jp')
Brand.find_or_create_by!(name: '夢醸', kana: 'むじょう', company: c)
Brand.find_or_create_by!(name: '福の宮', kana: 'ふくのみや', company: c)
c = Company.create_or_find_by!(name: '車多酒造', kana: 'しゃたしゅぞう', prefecture_code: 17, city: '白山市', address: '坊丸町60-1', tel: '076-275-1165', fax: '076-275-1866', website: 'https://www.tengumai.co.jp')
Brand.find_or_create_by!(name: '天狗舞', kana: 'てんぐまい', company: c)
Brand.find_or_create_by!(name: '五凜', kana: 'ごりん', company: c)
Brand.find_or_create_by!(name: 'shu re', kana: 'シュレ', company: c)
c = Company.create_or_find_by!(name: '吉田酒造店', kana: 'よしだしゅぞうてん', prefecture_code: 17, city: '白山市', address: '安吉町41', tel: '076-276-3311', fax: '076-276-3378', website: 'https://tedorigawa.com')
Brand.find_or_create_by!(name: 'You / U', kana: 'ゆう', company: c)
Brand.find_or_create_by!(name: '吉田蔵', kana: 'よしだぐら', company: c)
Brand.find_or_create_by!(name: 'いきな女', kana: 'いきなおんな', company: c)
Brand.find_or_create_by!(name: '友白髪', kana: 'ともしらが', company: c)
Brand.find_or_create_by!(name: '手取川', kana: 'てどりがわ', company: c)
c = Company.create_or_find_by!(name: '金谷酒造店', kana: 'かなやしゅぞうてん', prefecture_code: 17, city: '白山市', address: '安田町3-2', tel: '076-276-1177', fax: '076-276-4234', website: 'http://www.hakusan-takasago.jp')
Brand.find_or_create_by!(name: '高砂', kana: 'たかさご', company: c)
Brand.find_or_create_by!(name: '北美雪', kana: 'きたみゆき', company: c)
Brand.find_or_create_by!(name: '友白髪', kana: 'ともしらが', company: c)
c = Company.create_or_find_by!(name: '春成酒造店', kana: 'はるなりしゅぞうてん', prefecture_code: 17, city: '七尾市', address: '今町15', tel: '0767-52-0120', fax: '0767-52-7135', website: '')
Brand.find_or_create_by!(name: '春山', kana: 'はるやま', company: c)
c = Company.create_or_find_by!(name: '布施酒造店', kana: 'ふせしゅぞうてん', prefecture_code: 17, city: '七尾市', address: '三島町52-2', tel: '0767-53-0027', fax: '', website: '')
Brand.find_or_create_by!(name: '天平', kana: 'てんぺい', company: c)
c = Company.create_or_find_by!(name: '鶴野酒造店', kana: 'つるのしゅぞうてん', prefecture_code: 17, city: '鳳珠郡', address: '能登町鵜川19-64', tel: '0768-67-2311', fax: '0768-67-2312', website: 'https://www.taniizumi.com')
Brand.find_or_create_by!(name: '鶴と福', kana: 'つるとふく', company: c)
Brand.find_or_create_by!(name: '谷泉', kana: 'たにいずみ', company: c)
Brand.find_or_create_by!(name: '登雷', kana: 'とらい', company: c)
c = Company.create_or_find_by!(name: '数馬酒造', kana: 'かずましゅぞう', prefecture_code: 17, city: '鳳珠郡', address: '能登町宇出津ヘ36', tel: '0768-62-1200', fax: '0768-62-1201', website: 'https://chikuha.co.jp')
Brand.find_or_create_by!(name: 'Chikuha N', kana: 'ちくは えぬ', company: c)
Brand.find_or_create_by!(name: '竹葉', kana: 'ちくは', company: c)
Brand.find_or_create_by!(name: '閃', kana: 'せん', company: c)
Brand.find_or_create_by!(name: '深豊', kana: 'しんほう', company: c)
Brand.find_or_create_by!(name: 'NOTO', kana: 'のと', company: c)
c = Company.create_or_find_by!(name: '松波酒造', kana: 'まつなみしゅぞう', prefecture_code: 17, city: '鳳珠郡', address: '能登町松波30-114', tel: '0768-72-0005', fax: '0768-72-2348', website: 'http://www.o-eyama.com')
Brand.find_or_create_by!(name: '大江山', kana: 'おおえやま', company: c)
Brand.find_or_create_by!(name: '能登起舟', kana: 'のときしゅう', company: c)
Brand.find_or_create_by!(name: 'つづらの波', kana: 'つづらのなみ', company: c)
c = Company.create_or_find_by!(name: '櫻田酒造', kana: 'さくらだしゅぞう', prefecture_code: 17, city: '珠洲市', address: '蛸島町ソ93', tel: '0768-82-0508', fax: '0768-82-6628', website: 'https://sakurada.co.jp')
Brand.find_or_create_by!(name: '大慶', kana: 'たいけい', company: c)
Brand.find_or_create_by!(name: '初桜', kana: 'はつさくら', company: c)
Brand.find_or_create_by!(name: '能登桜', kana: 'のとざくら', company: c)
c = Company.create_or_find_by!(name: '宗玄酒造', kana: 'そうげんしゅぞう', prefecture_code: 17, city: '珠洲市', address: '宝立町宗玄24-22', tel: '0768-84-1314', fax: '0768-84-1315', website: 'http://www.sougen-shuzou.com')
Brand.find_or_create_by!(name: '宗玄', kana: 'そうげん', company: c)
c = Company.create_or_find_by!(name: '中野酒造', kana: 'なかのしゅぞう', prefecture_code: 17, city: '輪島市', address: '門前町広瀬ニ5-2', tel: '0768-42-0008', fax: '', website: '')
Brand.find_or_create_by!(name: '能登亀泉', kana: 'のとかめいずみ', company: c)
c = Company.create_or_find_by!(name: '沢田酒造店', kana: 'さわだしゅぞうてん', prefecture_code: 17, city: '輪島市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '白鳳', kana: 'はくほう', company: c)
Brand.find_or_create_by!(name: '能登のおやじ', kana: 'のとのおやじ', company: c)
Brand.find_or_create_by!(name: 'つばさ', kana: 'つばさ', company: c)
c = Company.create_or_find_by!(name: '日吉酒造店', kana: 'ひよししゅぞうてん', prefecture_code: 17, city: '輪島市', address: '河井町2-27-1', tel: '0768-22-0130', fax: '0768-22-9988', website: 'http://www.hiyoshisyuzou.com')
Brand.find_or_create_by!(name: '金瓢白駒', kana: 'きんぴょうしらこま', company: c)
Brand.find_or_create_by!(name: 'ささのつゆ', kana: 'ささのつゆ', company: c)
Brand.find_or_create_by!(name: 'おれの酒', kana: 'おれのさけ', company: c)
c = Company.create_or_find_by!(name: '清水酒造店', kana: 'しみずしゅぞうてん', prefecture_code: 17, city: '輪島市', address: '河井町1-18-1', tel: '0768-22-5858', fax: '0768-22-5868', website: 'http://www.notohomare.com')
Brand.find_or_create_by!(name: '千枚田', kana: 'せんまいだ', company: c)
Brand.find_or_create_by!(name: '能登誉', kana: 'のとほまれ', company: c)
c = Company.create_or_find_by!(name: '白藤酒造店', kana: 'はくとうしゅぞうてん', prefecture_code: 17, city: '輪島市', address: '鳳至町上町24', tel: '0768-22-2115', fax: '0768-22-5524', website: 'http://www.hakutousyuzou.jp')
Brand.find_or_create_by!(name: '寧音', kana: 'ねね', company: c)
Brand.find_or_create_by!(name: '奥能登の白菊', kana: 'おくのとのしらぎく', company: c)
c = Company.create_or_find_by!(name: '中島酒造店', kana: 'なかしましゅぞうてん', prefecture_code: 17, city: '輪島市', address: '鳳至町稲荷町8', tel: '0768-22-0018', fax: '0768-22-0018', website: 'https://www.notosuehiro.com')
Brand.find_or_create_by!(name: '杜夢', kana: 'とむ', company: c)
Brand.find_or_create_by!(name: '能登國', kana: 'のとぐに', company: c)
Brand.find_or_create_by!(name: '花おぼろ', kana: 'はなおぼろ', company: c)
Brand.find_or_create_by!(name: '能登末廣', kana: 'のとすえひろ', company: c)
c = Company.create_or_find_by!(name: '中納酒造', kana: 'なかのしゅぞう', prefecture_code: 17, city: '輪島市', address: '町野町寺山3-42', tel: '0768-32-1130', fax: '0768-32-1131', website: '')
Brand.find_or_create_by!(name: '若緑', kana: 'わかみどり', company: c)
c = Company.create_or_find_by!(name: '久世酒造店', kana: 'くぜしゅぞうてん', prefecture_code: 17, city: '河北郡', address: '津幡町清水イ122', tel: '076-289-2028', fax: '076-289-4606', website: 'http://www.choseimai.co.jp')
Brand.find_or_create_by!(name: '能登路', kana: 'のとじ', company: c)
Brand.find_or_create_by!(name: '長生舞', kana: 'ちょうせいまい', company: c)
c = Company.create_or_find_by!(name: '見砂酒造', kana: 'みさごしゅぞう', prefecture_code: 17, city: '羽咋郡', address: '宝達志水町宿4-43', tel: '0767-28-3151', fax: '0767-28-3152', website: '')
Brand.find_or_create_by!(name: '朱鷺の里', kana: 'ときのさと', company: c)
c = Company.create_or_find_by!(name: '御祖酒造', kana: 'みおやしゅぞう', prefecture_code: 17, city: '羽咋市', address: '大町イ8', tel: '0767-26-2320', fax: '0767-26-2339', website: 'http://mioya-sake.com')
Brand.find_or_create_by!(name: 'ほまれ', kana: 'ほまれ', company: c)
Brand.find_or_create_by!(name: '遊穂', kana: 'ゆうほ', company: c)
c = Company.create_or_find_by!(name: '二羽鶴酒造場', kana: 'にわづるしゅぞうじょう', prefecture_code: 17, city: '鹿島郡', address: '中能登町羽坂4-21-1', tel: '0767-74-0010', fax: '0767-74-0018', website: '')
Brand.find_or_create_by!(name: '二羽鶴', kana: 'にわづる', company: c)
c = Company.create_or_find_by!(name: '鳥屋酒造', kana: 'とりやしゅぞう', prefecture_code: 17, city: '鹿島郡', address: '中能登町一青ケ96', tel: '0767-74-0013', fax: '0767-74-1139', website: '')
Brand.find_or_create_by!(name: '池月', kana: 'いけづき', company: c)
