c = Company.create_or_find_by!(name: '宝酒造', kana: 'たからしゅぞう', prefecture_code: 26, city: '京都市下京区', address: '長刀鉾町20　四条烏丸ＦＴスクエア（四条通烏丸東入）', tel: '075-241-5110', fax: '075-211-6385', website: 'https://www.takarashuzo.co.jp')
Brand.find_or_create_by!(name: '松竹梅', kana: 'しょうちくばい', company: c)
Brand.find_or_create_by!(name: '豪快', kana: 'ごうかい', company: c)
Brand.find_or_create_by!(name: '松竹梅 天', kana: 'しょうちくばい てん', company: c)
Brand.find_or_create_by!(name: '松竹梅 昴', kana: 'しょうちくばい すばる', company: c)
c = Company.create_or_find_by!(name: '羽田酒造', kana: 'はねだしゅぞう', prefecture_code: 26, city: '京都市右京区', address: '京北周山町下台20', tel: '0771-52-0080', fax: '0771-52-1150', website: 'http://www.hanedashuzo.co.jp')
Brand.find_or_create_by!(name: '羽田', kana: 'はねだ', company: c)
Brand.find_or_create_by!(name: '脱兎', kana: 'だっと', company: c)
Brand.find_or_create_by!(name: '初日の出', kana: 'はつひので', company: c)
Brand.find_or_create_by!(name: '酒公杯', kana: 'しゅこうはい', company: c)
Brand.find_or_create_by!(name: '六友', kana: 'りくゆう', company: c)
c = Company.create_or_find_by!(name: '佐々木酒造', kana: 'ささきしゅぞう', prefecture_code: 26, city: '京都市上京区', address: '北伊勢屋町727　日暮通椹木町下る', tel: '075-841-8106', fax: '075-801-2582', website: 'http://jurakudai.com')
Brand.find_or_create_by!(name: '古都', kana: 'こと', company: c)
Brand.find_or_create_by!(name: 'まるたけえびす', kana: 'まるたけえびす', company: c)
Brand.find_or_create_by!(name: '西陣', kana: 'にしじん', company: c)
Brand.find_or_create_by!(name: '平安四神', kana: 'へいあんししん', company: c)
Brand.find_or_create_by!(name: '京生粋', kana: 'きょうきっすい', company: c)
Brand.find_or_create_by!(name: '聚楽第', kana: 'じゅらくだい', company: c)
c = Company.create_or_find_by!(name: '京都酒造組合', kana: 'きょうとしゅぞうくみあい', prefecture_code: 26, city: '京都市左京区', address: '吉田河原町1-6　エーデルハイム鴨川100', tel: '075-366-6246', fax: '075-366-6247', website: 'http://kyotosake.jp')
Brand.find_or_create_by!(name: '美しい鴨川', kana: 'うつくしいかもがわ', company: c)
c = Company.create_or_find_by!(name: '松井酒造', kana: 'まついしゅぞう', prefecture_code: 26, city: '京都市左京区', address: '吉田河原町1-6', tel: '075-771-0246', fax: '075-771-3630', website: 'https://matsuishuzo.com')
Brand.find_or_create_by!(name: '京千歳', kana: 'きょうちとせ', company: c)
Brand.find_or_create_by!(name: '富士千歳', kana: 'ふじちとせ', company: c)
Brand.find_or_create_by!(name: '京春雅', kana: 'きょーかすが', company: c)
Brand.find_or_create_by!(name: '祇園ばやし', kana: 'ぎおんばやし', company: c)
Brand.find_or_create_by!(name: '神蔵', kana: 'かぐら', company: c)
Brand.find_or_create_by!(name: '金瓢', kana: 'きんぴょう', company: c)
c = Company.create_or_find_by!(name: '城陽酒造', kana: 'じょうようしゅぞう', prefecture_code: 26, city: '城陽市', address: '奈島久保野34-1', tel: '0774-52-0003', fax: '0774-55-5552', website: 'http://www.joyo-shuzo.co.jp')
Brand.find_or_create_by!(name: '伏見誉', kana: 'ふしみほまれ', company: c)
Brand.find_or_create_by!(name: '城陽', kana: 'じょうよう', company: c)
Brand.find_or_create_by!(name: '徳次郎', kana: 'とくじろう', company: c)
Brand.find_or_create_by!(name: '陽', kana: 'はる', company: c)
c = Company.create_or_find_by!(name: '東山酒造', kana: 'ひがしやましゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '塩屋町223', tel: '075-604-1880', fax: '075-604-1886', website: '')
Brand.find_or_create_by!(name: '魯山人', kana: 'ろさんじん', company: c)
Brand.find_or_create_by!(name: '坤滴', kana: 'こんてき', company: c)
c = Company.create_or_find_by!(name: '山本本家', kana: 'やまもとほんけ', prefecture_code: 26, city: '京都市伏見区', address: '上油掛町36-1', tel: '075-611-0211', fax: '075-601-0011', website: 'http://www.yamamotohonke.jp')
Brand.find_or_create_by!(name: '松の翆', kana: 'まつのみどり', company: c)
Brand.find_or_create_by!(name: '鉄斎', kana: 'てっさい', company: c)
Brand.find_or_create_by!(name: '水のしらべ', kana: 'みずのしらべ', company: c)
Brand.find_or_create_by!(name: '神聖', kana: 'しんせい', company: c)
Brand.find_or_create_by!(name: '花清水', kana: 'はなしみず', company: c)
Brand.find_or_create_by!(name: '明ごころ', kana: 'あけごころ', company: c)
Brand.find_or_create_by!(name: 'かぐや姫', kana: 'かぐやひめ', company: c)
Brand.find_or_create_by!(name: '京伝来 さらなり', kana: 'きょうでんらい さらなり', company: c)
Brand.find_or_create_by!(name: '蒲田紀行', kana: 'かまたきこう', company: c)
Brand.find_or_create_by!(name: '京舞妓', kana: 'きょうまいこ', company: c)
Brand.find_or_create_by!(name: '名誉冠', kana: 'めいよかん', company: c)
c = Company.create_or_find_by!(name: '藤岡酒造', kana: 'ふじおかしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '今町672-1', tel: '075-611-4666', fax: '075-611-4343', website: 'http://www.sookuu.net')
Brand.find_or_create_by!(name: '蒼空', kana: 'そうくう', company: c)
c = Company.create_or_find_by!(name: '平和酒造', kana: 'へいわしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '東組町698', tel: '075-601-0012', fax: '075-602-0015', website: '')
Brand.find_or_create_by!(name: '慶長', kana: 'けいちょう', company: c)
c = Company.create_or_find_by!(name: '都鶴酒造', kana: 'みやこつるしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '御駕籠町151', tel: '075-601-5301', fax: '075-611-8281', website: 'http://www.miyakotsuru.co.jp')
Brand.find_or_create_by!(name: '伏見正宗', kana: 'ふしみまさむね', company: c)
Brand.find_or_create_by!(name: '都鶴', kana: 'みやこつる', company: c)
c = Company.create_or_find_by!(name: '松山酒造', kana: 'まつやましゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '東堺町472', tel: '075-601-2528', fax: '075-601-0100', website: '')
Brand.find_or_create_by!(name: '明君', kana: 'めいくん', company: c)
c = Company.create_or_find_by!(name: '玉乃光酒造', kana: 'たまのひかりしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '東堺町545-2', tel: '075-611-5000', fax: '075-601-0004', website: 'http://www.tamanohikari.co.jp')
Brand.find_or_create_by!(name: 'TAMA', kana: 'たま', company: c)
Brand.find_or_create_by!(name: '青まねきつね', kana: 'あおまねきつね', company: c)
Brand.find_or_create_by!(name: '玉乃光', kana: 'たまのひかり', company: c)
c = Company.create_or_find_by!(name: '鶴正酒造', kana: 'つるまさしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '東堺町474', tel: '075-611-0221', fax: '075-601-6385', website: '')
Brand.find_or_create_by!(name: '鶴正宗', kana: 'つるまさむね', company: c)
c = Company.create_or_find_by!(name: '日々醸造', kana: 'にちにちじょうぞう', prefecture_code: 26, city: '京都市伏見区', address: '城通町628', tel: '', fax: '', website: 'https://sake.inc')
Brand.find_or_create_by!(name: '日日', kana: 'にちにち', company: c)
c = Company.create_or_find_by!(name: '共同酒造', kana: 'きょうどうしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '下板橋町630-3', tel: '075-611-3221', fax: '075-611-3221', website: '')
Brand.find_or_create_by!(name: '美山', kana: 'みやま', company: c)
c = Company.create_or_find_by!(name: '山本勘蔵商店', kana: 'やまもとかんぞうしょうてん', prefecture_code: 26, city: '京都市伏見区', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '鷹取', kana: 'たかとり', company: c)
c = Company.create_or_find_by!(name: '松本酒造', kana: 'まつもとしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '横大路三栖大黒町7', tel: '075-611-1238', fax: '', website: 'https://sawayamatsumoto.com')
Brand.find_or_create_by!(name: '呑足味知', kana: 'のみたりてあじをしる', company: c)
Brand.find_or_create_by!(name: '日出盛', kana: 'ひのでさかり', company: c)
Brand.find_or_create_by!(name: '桃の滴', kana: 'もものしずく', company: c)
Brand.find_or_create_by!(name: '澤屋まつもと', kana: 'さわやまつもと', company: c)
c = Company.create_or_find_by!(name: '齊藤酒造', kana: 'さいとうしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '横大路三栖山城屋敷町105', tel: '075-611-2124', fax: '075-602-8331', website: 'https://www.eikun.com')
Brand.find_or_create_by!(name: '英勲', kana: 'えいくん', company: c)
c = Company.create_or_find_by!(name: '黄桜酒造', kana: 'きざくらしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '横大路下三栖梶原町53', tel: '075-611-4101', fax: '075-622-3510', website: 'https://kizakura.co.jp')
Brand.find_or_create_by!(name: '銀河交響曲', kana: 'ぎんがこうきょうきょく', company: c)
Brand.find_or_create_by!(name: '黄桜', kana: 'きざくら', company: c)
Brand.find_or_create_by!(name: 'ピアノ', kana: 'ぴあの', company: c)
c = Company.create_or_find_by!(name: '豊澤本店', kana: 'とよさわほんてん', prefecture_code: 26, city: '京都市伏見区', address: '榎町769', tel: '075-601-5341', fax: '075-622-5620', website: 'http://homepage2.nifty.com/housyuku')
Brand.find_or_create_by!(name: '豊祝', kana: 'ほうしゅく', company: c)
c = Company.create_or_find_by!(name: '招徳酒造', kana: 'しょうとくしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '舞台町16', tel: '075-611-0296', fax: '075-611-0298', website: 'http://www.shoutoku.co.jp')
Brand.find_or_create_by!(name: '招徳', kana: 'しょうとく', company: c)
c = Company.create_or_find_by!(name: '京姫酒造', kana: 'きょうひめしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '山崎町343', tel: '075-622-2323', fax: '075-621-8486', website: '')
Brand.find_or_create_by!(name: '京姫', kana: 'きょうひめ', company: c)
c = Company.create_or_find_by!(name: '北川本家', kana: 'きたがわほんけ', prefecture_code: 26, city: '京都市伏見区', address: '村上町370-6', tel: '075-611-1271', fax: '075-611-1273', website: 'https://www.tomio-sake.co.jp')
Brand.find_or_create_by!(name: 'ふり袖', kana: 'ふりそで', company: c)
Brand.find_or_create_by!(name: '虎の御門', kana: 'とらのごもん', company: c)
Brand.find_or_create_by!(name: '富翁', kana: 'とみおう', company: c)
Brand.find_or_create_by!(name: '祇園物語', kana: 'ぎおんものがたり', company: c)
Brand.find_or_create_by!(name: '宝寿盃', kana: 'ほうじゅはい', company: c)
Brand.find_or_create_by!(name: '乾風', kana: 'あなぜ', company: c)
c = Company.create_or_find_by!(name: '名誉冠酒造', kana: 'めいよかんしゅぞう', prefecture_code: 26, city: '京都市伏見区', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '名誉冠', kana: 'めいよかん', company: c)
c = Company.create_or_find_by!(name: '増田徳兵衛商店', kana: 'ますだとくべえしょうてん', prefecture_code: 26, city: '京都市伏見区', address: '下鳥羽長田町135', tel: '075-611-5151', fax: '075-611-8118', website: 'https://www.tsukinokatsura.co.jp')
Brand.find_or_create_by!(name: '月の桂', kana: 'つきのかつら', company: c)
Brand.find_or_create_by!(name: '抱腹絶倒', kana: 'ほうふくぜっとう', company: c)
Brand.find_or_create_by!(name: '吃驚仰天', kana: 'びっくりぎょうてん', company: c)
Brand.find_or_create_by!(name: 'おもてなし 伏味', kana: 'おもてなし ふしみ', company: c)
Brand.find_or_create_by!(name: '稼ぎ頭', kana: 'かせぎがしら', company: c)
c = Company.create_or_find_by!(name: '月桂冠', kana: 'げっけいかん', prefecture_code: 26, city: '京都市伏見区', address: '南浜町247', tel: '075-623-2105', fax: '075-623-2048', website: 'https://www.gekkeikan.co.jp')
Brand.find_or_create_by!(name: '京山水', kana: 'きょうさんすい', company: c)
Brand.find_or_create_by!(name: '月桂冠', kana: 'げっけいかん', company: c)
Brand.find_or_create_by!(name: 'おしゃべりクジラ', kana: 'おしゃべりくじら', company: c)
c = Company.create_or_find_by!(name: 'キンシ正宗', kana: 'きんしまさむね', prefecture_code: 26, city: '京都市伏見区', address: '新町11丁目337-1', tel: '075-611-5201', fax: '075-611-0080', website: 'http://www.kinshimasamune.com')
Brand.find_or_create_by!(name: 'キンシ正宗', kana: 'きんしまさむね', company: c)
Brand.find_or_create_by!(name: 'BONITA', kana: 'ボニータ', company: c)
Brand.find_or_create_by!(name: '荒武者', kana: 'あらむしゃ', company: c)
Brand.find_or_create_by!(name: '藤袴', kana: 'ふじばかま', company: c)
c = Company.create_or_find_by!(name: '京都酒造', kana: 'きょうとしゅぞう', prefecture_code: 26, city: '木津川市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '都正宗', kana: 'みやこまさむね', company: c)
c = Company.create_or_find_by!(name: '相綴酒造', kana: 'そうてつしゅぞう', prefecture_code: 26, city: '木津川市', address: '山城町綺田出垣外33-1', tel: '0774-86-3013', fax: '', website: '')
Brand.find_or_create_by!(name: 'いづみ川', kana: 'いづみかわ', company: c)
c = Company.create_or_find_by!(name: '河守醸造', kana: 'こうもりじょうぞう', prefecture_code: 26, city: '福知山市', address: '大江町関', tel: '', fax: '', website: '')
Brand.find_or_create_by!(name: 'かさ鶴', kana: 'かさづる', company: c)
c = Company.create_or_find_by!(name: '東和酒造', kana: 'とうわしゅぞう', prefecture_code: 26, city: '福知山市', address: '上野115', tel: '0773-35-0008', fax: '0773-35-0604', website: 'http://towa-shuzou.jp')
Brand.find_or_create_by!(name: '六歓', kana: 'ろっかん', company: c)
Brand.find_or_create_by!(name: '福知三萬二千石', kana: 'ふくちさんまんにせんごく', company: c)
Brand.find_or_create_by!(name: '武勇', kana: 'ぶゆう', company: c)
c = Company.create_or_find_by!(name: '岡野酒造場', kana: 'おかのしゅぞうじょう', prefecture_code: 26, city: '福知山市', address: '野花1', tel: '0773-33-2008', fax: '0773-33-3110', website: '')
Brand.find_or_create_by!(name: 'ゆら川', kana: 'ゆらがわ', company: c)
c = Company.create_or_find_by!(name: '大石酒造', kana: 'おおいししゅぞう', prefecture_code: 26, city: '亀岡市', address: 'ひえ田野町佐伯垣内亦13', tel: '0771-22-0632', fax: '0771-23-2188', website: 'https://www.okinazuru.co.jp')
Brand.find_or_create_by!(name: '明智越', kana: 'あけちごえ', company: c)
Brand.find_or_create_by!(name: '美山 てんごり', kana: 'みやま てんごり', company: c)
Brand.find_or_create_by!(name: '翁鶴', kana: 'おきなつる', company: c)
c = Company.create_or_find_by!(name: '丹山酒造', kana: 'たんざんしゅぞう', prefecture_code: 26, city: '亀岡市', address: '横町7', tel: '0771-22-0066', fax: '0771-22-2087', website: 'http://www.tanzan.co.jp')
Brand.find_or_create_by!(name: '京の旬', kana: 'きょうのしゅん', company: c)
Brand.find_or_create_by!(name: '飯櫃', kana: 'ぼんき', company: c)
Brand.find_or_create_by!(name: '渚', kana: 'なぎさ', company: c)
Brand.find_or_create_by!(name: '竹林群虎図', kana: 'ちくりんぐんとらず', company: c)
Brand.find_or_create_by!(name: '日出る国', kana: 'ひいずるくに', company: c)
Brand.find_or_create_by!(name: '完熟', kana: 'かんじゅく', company: c)
Brand.find_or_create_by!(name: '風神雷神', kana: 'ふうじんらいじん', company: c)
Brand.find_or_create_by!(name: '天', kana: 'きわみ', company: c)
Brand.find_or_create_by!(name: '雪月花 嵐山', kana: 'せつげつか あらしやま', company: c)
Brand.find_or_create_by!(name: '丹山', kana: 'たんざん', company: c)
c = Company.create_or_find_by!(name: '関酒造', kana: 'せきしゅぞう', prefecture_code: 26, city: '亀岡市', address: '紺屋町26', tel: '0771-22-0056', fax: '', website: '')
Brand.find_or_create_by!(name: 'この花桜', kana: 'このはなざくら', company: c)
c = Company.create_or_find_by!(name: '三盛酒造', kana: 'さんせいしゅぞう', prefecture_code: 26, city: '船井郡', address: '京丹波町富田坪井55', tel: '0771-82-3051', fax: '0771-82-3195', website: '')
Brand.find_or_create_by!(name: '丹波しずく', kana: 'たんばしずく', company: c)
Brand.find_or_create_by!(name: '祝瓢', kana: 'しゅくひょう', company: c)
c = Company.create_or_find_by!(name: '若宮酒造', kana: 'わかみやしゅぞう', prefecture_code: 26, city: '綾部市', address: '味方町薬師前4', tel: '0773-42-0268', fax: '0773-43-0268', website: 'http://www5.nkansai.ne.jp/com/ayakomachi')
Brand.find_or_create_by!(name: '丹ノ国', kana: 'にのくに', company: c)
Brand.find_or_create_by!(name: '綾小町', kana: 'あやこまち', company: c)
c = Company.create_or_find_by!(name: '池田酒造', kana: 'いけだしゅぞう', prefecture_code: 26, city: '舞鶴市', address: '中山32', tel: '0773-82-0005', fax: '0773-82-0935', website: 'http://www.ikekumo.com')
Brand.find_or_create_by!(name: '加佐一陽', kana: 'かさいちよう', company: c)
Brand.find_or_create_by!(name: '海風', kana: 'うみかぜ', company: c)
Brand.find_or_create_by!(name: '池雲', kana: 'いけくも', company: c)
c = Company.create_or_find_by!(name: 'ハクレイ酒造', kana: 'はくれいしゅぞう', prefecture_code: 26, city: '宮津市', address: '字由良949', tel: '0772-26-0001', fax: '0772-26-0123', website: 'http://www.hakurei.co.jp')
Brand.find_or_create_by!(name: 'どっこいせ', kana: 'どっこいせ', company: c)
Brand.find_or_create_by!(name: '酒呑童子', kana: 'しゅてんどうじ', company: c)
Brand.find_or_create_by!(name: '大鬼', kana: 'おおおに', company: c)
Brand.find_or_create_by!(name: '大杉', kana: 'おおすぎ', company: c)
Brand.find_or_create_by!(name: '燗囃', kana: 'かんばやし', company: c)
Brand.find_or_create_by!(name: '香田', kana: 'こうでん', company: c)
Brand.find_or_create_by!(name: '京石川 かたり酒', kana: 'きょういしかわ かたりざけ', company: c)
Brand.find_or_create_by!(name: '白嶺', kana: 'はくれい', company: c)
c = Company.create_or_find_by!(name: '向井酒造', kana: 'むかいしゅぞう', prefecture_code: 26, city: '与謝郡', address: '伊根町平田67', tel: '0772-32-0003', fax: '0772-32-0199', website: 'http://www.kuramoto-mukai.jp')
Brand.find_or_create_by!(name: '益荒猛男', kana: 'ますらたけお', company: c)
Brand.find_or_create_by!(name: '伊根満開', kana: 'いねまんかい', company: c)
Brand.find_or_create_by!(name: 'ええにょぼ', kana: 'ええにょぼ', company: c)
Brand.find_or_create_by!(name: '京の春', kana: 'きょうのはる', company: c)
c = Company.create_or_find_by!(name: '峰山酒造', kana: 'みねやましゅぞう', prefecture_code: 26, city: '京丹後市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '麗峰', kana: 'れいほう', company: c)
c = Company.create_or_find_by!(name: '吉岡酒造場', kana: 'よしおかしゅぞうじょう', prefecture_code: 26, city: '京丹後市', address: '弥栄町溝谷1139', tel: '0772-65-2020', fax: '0772-65-3275', website: 'http://www.yoshinoyama-tango.com')
Brand.find_or_create_by!(name: '吉野山', kana: 'よしのやま', company: c)
c = Company.create_or_find_by!(name: '竹野酒造', kana: 'たけのしゅぞう', prefecture_code: 26, city: '京丹後市', address: '弥栄町溝谷3622-1', tel: '0772-65-2021', fax: '0772-65-2871', website: 'http://www.yasakaturu.co.jp')
Brand.find_or_create_by!(name: '蔵舞', kana: 'くらぶ', company: c)
Brand.find_or_create_by!(name: '弥栄鶴', kana: 'やさかつる', company: c)
Brand.find_or_create_by!(name: 'きょうおとめ', kana: 'きょうおとめ', company: c)
Brand.find_or_create_by!(name: 'むきだし', kana: 'むきだし', company: c)
c = Company.create_or_find_by!(name: '永雄酒造', kana: 'ながおしゅぞう', prefecture_code: 26, city: '京丹後市', address: '丹後町中浜643', tel: '0772-76-0002', fax: '0772-76-1156', website: '')
Brand.find_or_create_by!(name: '最中屋茂兵衛', kana: 'もなかやもへい', company: c)
Brand.find_or_create_by!(name: '旭桜', kana: 'あさひさくら', company: c)
c = Company.create_or_find_by!(name: '長老', kana: 'ちょうろう', prefecture_code: 26, city: '船井郡', address: '京丹波町本庄ノヲテ5', tel: '0771-84-0018', fax: '0771-84-0148', website: 'http://www.chourou.co.jp')
Brand.find_or_create_by!(name: '長老', kana: 'ちょうろう', company: c)
c = Company.create_or_find_by!(name: '白糸酒造', kana: 'しらいとしゅぞう', prefecture_code: 26, city: '宮津市', address: '江尻382', tel: '0772-27-0001', fax: '', website: 'http://sake-shiraito.com')
Brand.find_or_create_by!(name: '天橋立へようきなった', kana: 'あまのはしだてへようきなった', company: c)
Brand.find_or_create_by!(name: '白糸', kana: 'しらいと', company: c)
c = Company.create_or_find_by!(name: '細井酒造', kana: 'ほそいしゅぞう', prefecture_code: 26, city: '与謝郡', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '平安京自慢', kana: 'へいあんきょうじまん', company: c)
c = Company.create_or_find_by!(name: '与謝娘酒造', kana: 'よさむすめしゅぞう', prefecture_code: 26, city: '与謝郡', address: '与謝野町字与謝2-2', tel: '0772-42-2834', fax: '0772-43-1117', website: '')
Brand.find_or_create_by!(name: 'よさ娘', kana: 'よさむすめ', company: c)
Brand.find_or_create_by!(name: '丹後七姫', kana: 'たんごしちひめ', company: c)
c = Company.create_or_find_by!(name: '谷口酒造', kana: 'たにぐちしゅぞう', prefecture_code: 26, city: '与謝郡', address: '与謝野町与謝70-2', tel: '0772-42-2018', fax: '', website: 'http://若冲.com')
Brand.find_or_create_by!(name: '丹後物語', kana: 'たんごものがたり', company: c)
Brand.find_or_create_by!(name: '丹後王国', kana: 'たんごおうこく', company: c)
Brand.find_or_create_by!(name: '芝の井', kana: 'しばのい', company: c)
Brand.find_or_create_by!(name: '若冲', kana: 'じゃくちゅう', company: c)
c = Company.create_or_find_by!(name: '白杉酒造', kana: 'しらすぎしゅぞう', prefecture_code: 26, city: '京丹後市', address: '大宮町周枳954', tel: '0772-64-2101', fax: '0772-64-2154', website: 'https://ja-jp.facebook.com/235760923200660')
Brand.find_or_create_by!(name: '銀シャリ', kana: 'ぎんしゃり', company: c)
Brand.find_or_create_by!(name: 'BLACK SWAN', kana: 'ブラックスワン', company: c)
Brand.find_or_create_by!(name: '丹後のヒカリ', kana: 'たんごのひかり', company: c)
Brand.find_or_create_by!(name: '白木久', kana: 'しらきく', company: c)
c = Company.create_or_find_by!(name: '大同酒造', kana: 'だいどうしゅぞう', prefecture_code: 26, city: '京丹後市', address: '大宮町奥大野 226', tel: '0772-64-2031', fax: '', website: '')
Brand.find_or_create_by!(name: '梅門若竹', kana: 'ばいもんわかたけ', company: c)
c = Company.create_or_find_by!(name: '熊野酒造', kana: 'くまのしゅぞう', prefecture_code: 26, city: '京丹後市', address: '久美浜町45-1', tel: '0772-82-0019', fax: '0772-82-1594', website: 'http://www.kuminoura.com')
Brand.find_or_create_by!(name: '杜氏の独り言', kana: 'とうじのひとりごと', company: c)
Brand.find_or_create_by!(name: '亀屋', kana: 'かめや', company: c)
Brand.find_or_create_by!(name: '久美の浦', kana: 'くみのうら', company: c)
c = Company.create_or_find_by!(name: '木下酒造', kana: 'きのしたしゅぞう', prefecture_code: 26, city: '京丹後市', address: '久美浜町甲山1512', tel: '0772-82-0071', fax: '0772-82-1770', website: 'https://www.sake-tamagawa.com')
Brand.find_or_create_by!(name: '玉川', kana: 'たまがわ', company: c)
Brand.find_or_create_by!(name: 'Time Machine', kana: 'タイムマシーン', company: c)
