c = Company.create_or_find_by!(name: '呉春', kana: 'ごしゅん', prefecture_code: 27, city: '池田市', address: '綾羽1-2-2', tel: '072-751-2023', fax: '', website: '')
Brand.find_or_create_by!(name: '呉春', kana: 'ごしゅん', company: c)
c = Company.create_or_find_by!(name: '吉田酒造', kana: 'よしだしゅぞう', prefecture_code: 27, city: '池田市', address: '栄本町7-10', tel: '072-751-2063', fax: '072-753-8881', website: 'http://www.midori-1.jp')
Brand.find_or_create_by!(name: '緑一', kana: 'みどりいち', company: c)
c = Company.create_or_find_by!(name: '秋鹿酒造', kana: 'あきしかしゅぞう', prefecture_code: 27, city: '豊能郡', address: '能勢町倉垣1007', tel: '072-737-0013', fax: '072-737-0840', website: '')
Brand.find_or_create_by!(name: '秋鹿', kana: 'あきしか', company: c)
c = Company.create_or_find_by!(name: '中尾酒造', kana: 'なかおしゅぞう', prefecture_code: 27, city: '茨木市', address: '宿久庄5-32-12', tel: '072-643-2226', fax: '072-643-2518', website: 'http://bongu.jugem.jp')
Brand.find_or_create_by!(name: '艶正宗', kana: 'つやまさむね', company: c)
Brand.find_or_create_by!(name: '凡愚', kana: 'ぼんぐ', company: c)
Brand.find_or_create_by!(name: '龍泉', kana: 'りゅうせん', company: c)
Brand.find_or_create_by!(name: '見山', kana: 'みやま', company: c)
c = Company.create_or_find_by!(name: '高島酒造', kana: 'たかしましゅぞう', prefecture_code: 27, city: '茨木市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '寿盃', kana: 'じゅはい', company: c)
c = Company.create_or_find_by!(name: '寿酒造', kana: 'ことぶきしゅぞう', prefecture_code: 27, city: '高槻市', address: '富田町3-26-12', tel: '072-696-0003', fax: '072-693-1533', website: 'http://www.kuninocho.jp')
Brand.find_or_create_by!(name: '國乃長', kana: 'くにのちょう', company: c)
c = Company.create_or_find_by!(name: '清鶴酒造', kana: 'きよつるしゅぞう', prefecture_code: 27, city: '高槻市', address: '富田町6-5-3', tel: '072-696-0014', fax: '072-692-0014', website: 'http://www.kiyotsuru.jp')
Brand.find_or_create_by!(name: '清鶴', kana: 'きよつる', company: c)
c = Company.create_or_find_by!(name: '大門酒造', kana: 'だいもんしゅぞう', prefecture_code: 27, city: '交野市', address: '森南3-12-1', tel: '072-891-0353', fax: '072-891-0354', website: 'https://www.daimonbrewery.com')
Brand.find_or_create_by!(name: 'むくね', kana: 'むくね', company: c)
Brand.find_or_create_by!(name: '山嵐 山風', kana: 'やまあらし やまかぜ', company: c)
Brand.find_or_create_by!(name: '大門 DAIMON', kana: 'だいもん', company: c)
Brand.find_or_create_by!(name: '利休梅', kana: 'りきゅうばい', company: c)
c = Company.create_or_find_by!(name: '山野酒造', kana: 'やまのしゅぞう', prefecture_code: 27, city: '交野市', address: '私部7-11-2', tel: '072-891-1046', fax: '072-891-1846', website: 'https://www.katanosakura.com')
Brand.find_or_create_by!(name: '片野桜', kana: 'かたのさくら', company: c)
Brand.find_or_create_by!(name: '彦星の山', kana: 'ひこぼしのやま', company: c)
Brand.find_or_create_by!(name: '織姫の里', kana: 'おりひめのさと', company: c)
Brand.find_or_create_by!(name: '寝屋の長者', kana: 'ねやのちょうじゃ', company: c)
c = Company.create_or_find_by!(name: '藤本雅一酒造醸', kana: 'ふじもとただひとしゅぞうじょう', prefecture_code: 27, city: '藤井寺市', address: '藤井寺2-1-10', tel: '072-955-0018', fax: '072-955-0018', website: 'http://www.fujimotosyuzou.com')
Brand.find_or_create_by!(name: '井真成', kana: 'いのまなり', company: c)
Brand.find_or_create_by!(name: '玉瑞', kana: 'たまみず', company: c)
Brand.find_or_create_by!(name: '雅一', kana: 'みやびいち', company: c)
Brand.find_or_create_by!(name: '冨士正', kana: 'ふじまさ', company: c)
Brand.find_or_create_by!(name: '松花鶴', kana: 'しょうかづる', company: c)
c = Company.create_or_find_by!(name: '西條', kana: 'さいじょう', prefecture_code: 27, city: '河内長野市', address: '長野町12-18', tel: '0721-55-1101', fax: '0721-56-1101', website: 'http://amanosake.com')
Brand.find_or_create_by!(name: '天野酒', kana: 'あまのさけ', company: c)
c = Company.create_or_find_by!(name: '利休蔵', kana: 'りきゅうぐら', prefecture_code: 27, city: '堺市堺区', address: '甲斐町西3丁3-4', tel: '072-222-0707', fax: '', website: 'https://sennorikyu-nihonshu.jp')
Brand.find_or_create_by!(name: '灘泉', kana: 'なだいずみ', company: c)
Brand.find_or_create_by!(name: '千利休', kana: 'せんのりきゅう', company: c)
c = Company.create_or_find_by!(name: '元朝', kana: 'がんちょう', prefecture_code: 27, city: '岸和田市', address: '並松町22-30', tel: '0724-38-1518', fax: '0724-22-8528', website: 'https://gancho-sake.jimdo.com')
Brand.find_or_create_by!(name: '篁', kana: 'たかむら', company: c)
Brand.find_or_create_by!(name: '元朝', kana: 'がんちょう', company: c)
c = Company.create_or_find_by!(name: '井坂酒造場', kana: 'いさかしゅぞうじょう', prefecture_code: 27, city: '岸和田市', address: '稲葉町117', tel: '072-479-0074', fax: '', website: '')
Brand.find_or_create_by!(name: '三輪福', kana: 'みわふく', company: c)
Brand.find_or_create_by!(name: 'だんじり', kana: 'だんじり', company: c)
c = Company.create_or_find_by!(name: '寺田酒造場', kana: 'てらだしゅぞうじょう', prefecture_code: 27, city: '貝塚市', address: '名越808-13', tel: '0724-46-1680', fax: '0724-46-2509', website: '')
Brand.find_or_create_by!(name: '千両菊', kana: 'せんりょうぎく', company: c)
Brand.find_or_create_by!(name: '秀長', kana: 'しゅうちょう', company: c)
c = Company.create_or_find_by!(name: '北庄司酒造店', kana: 'きたしょうじしゅぞうてん', prefecture_code: 27, city: '泉佐野市', address: '日根野3173', tel: '072-468-0850', fax: '072-467-2455', website: 'http://www.kitashouji.jp')
Brand.find_or_create_by!(name: '荘の郷', kana: 'しょうのさと', company: c)
c = Company.create_or_find_by!(name: '田原酒造', kana: 'たはらしゅぞう', prefecture_code: 27, city: '泉南郡', address: '田尻町嘉祥寺904', tel: '0724-65-0066', fax: '', website: '')
Brand.find_or_create_by!(name: '虎勢', kana: 'こせい', company: c)
Brand.find_or_create_by!(name: '若夫婦', kana: 'わかふうふ', company: c)
c = Company.create_or_find_by!(name: '浪花酒造', kana: 'なにわしゅぞう', prefecture_code: 27, city: '阪南市', address: '尾崎町3-13-6', tel: '072-472-0032', fax: '072-472-5000', website: 'http://www.naniwamasamune.com')
Brand.find_or_create_by!(name: '無我無心', kana: 'むがむしん', company: c)
Brand.find_or_create_by!(name: '前代未聞', kana: 'ぜんだいみもん', company: c)
Brand.find_or_create_by!(name: 'さか松', kana: 'さかまつ', company: c)
Brand.find_or_create_by!(name: '彦', kana: 'ひこ', company: c)
Brand.find_or_create_by!(name: '波有手', kana: 'ぼうで', company: c)
Brand.find_or_create_by!(name: '浪花正宗', kana: 'なにわまさむね', company: c)
Brand.find_or_create_by!(name: 'Retro PoRice Hannan', kana: 'レトロポリスはんなん', company: c)
