c = Company.create_or_find_by!(name: '岡山ZARU', kana: 'おかやまざる', prefecture_code: 33, city: '', address: '', tel: '', fax: '', website: 'http://okayamazaru.seesaa.net')
Brand.find_or_create_by!(name: 'ORIGIN', kana: 'オリジン', company: c)
c = Company.create_or_find_by!(name: '萬歳酒造', kana: 'ばんざいしゅぞう', prefecture_code: 33, city: '岡山市', address: '旭本町1-38', tel: '086-222-3836', fax: '086-222-3836', website: 'http://homepage2.nifty.com/manzai-syuzo')
Brand.find_or_create_by!(name: 'さつき心', kana: 'さつきごころ', company: c)
c = Company.create_or_find_by!(name: '板野酒造場', kana: 'いたのしゅぞうじょう', prefecture_code: 33, city: '岡山市北区', address: '一宮35番地', tel: '086-284-1161', fax: '086-284-2387', website: 'https://www.ginpoo.co.jp')
Brand.find_or_create_by!(name: 'きびの吟風', kana: 'きびのぎんぷう', company: c)
c = Company.create_or_find_by!(name: '板野酒造本店', kana: 'いたのしゅぞうほんてん', prefecture_code: 33, city: '岡山市北区', address: '大井2272', tel: '086-295-0025', fax: '086-295-2132', website: 'http://www.futamo.jp')
Brand.find_or_create_by!(name: '二面', kana: 'ふたも', company: c)
Brand.find_or_create_by!(name: '鬼ノ城', kana: 'きのじょう', company: c)
c = Company.create_or_find_by!(name: '利守酒造', kana: 'としもりしゅぞう', prefecture_code: 33, city: '赤磐市', address: '西軽部762-1', tel: '086-957-3117', fax: '086-957-3790', website: 'https://www.sakehitosuji.co.jp')
Brand.find_or_create_by!(name: '酒一筋', kana: 'さけひとすじ', company: c)
Brand.find_or_create_by!(name: '遥', kana: 'はるか', company: c)
Brand.find_or_create_by!(name: '天下人', kana: 'てんかびと', company: c)
c = Company.create_or_find_by!(name: '小坂酒造', kana: 'こさかしゅぞう', prefecture_code: 33, city: '赤磐市', address: '山口265-1', tel: '086-957-3023', fax: '086-957-3146', website: 'http://www.turunoike.co.jp')
Brand.find_or_create_by!(name: '鶴の池', kana: 'つるのいけ', company: c)
c = Company.create_or_find_by!(name: '小宮山酒造', kana: 'こみやましゅぞう', prefecture_code: 33, city: '赤磐市', address: '周匝1524-1', tel: '086-954-0411', fax: '', website: '')
Brand.find_or_create_by!(name: '日月', kana: 'じつげつ', company: c)
c = Company.create_or_find_by!(name: '山本酒造', kana: 'やまもとしゅぞう', prefecture_code: 33, city: '美作市', address: '福本577', tel: '0868-74-3165', fax: '0868-74-3287', website: '')
Brand.find_or_create_by!(name: '古代', kana: 'こだい', company: c)
Brand.find_or_create_by!(name: '喜久娘', kana: 'きくむすめ', company: c)
c = Company.create_or_find_by!(name: '遠藤酒造場', kana: 'えんどうしゅぞうじょう', prefecture_code: 33, city: '美作市', address: '福本610', tel: '0868-74-2001', fax: '0868-74-2002', website: '')
Brand.find_or_create_by!(name: '光露', kana: 'こうろ', company: c)
c = Company.create_or_find_by!(name: '服部本家酒造場', kana: 'はっとりほんけしゅぞうじょう', prefecture_code: 33, city: '瀬戸内市', address: '牛窓町牛窓3849', tel: '0869-34-2047', fax: '0869-34-5960', website: '')
Brand.find_or_create_by!(name: '大古酒', kana: 'だいこしゅ', company: c)
Brand.find_or_create_by!(name: '折鶴', kana: 'おりづる', company: c)
Brand.find_or_create_by!(name: '有春', kana: 'ゆうしゅん', company: c)
c = Company.create_or_find_by!(name: '高祖酒造', kana: 'こうそしゅぞう', prefecture_code: 33, city: '瀬戸内市', address: '牛窓町牛窓4943-1', tel: '0869-34-2002', fax: '0869-34-2003', website: 'http://www.kouso-senju.co.jp')
Brand.find_or_create_by!(name: '千寿', kana: 'せんじゅ', company: c)
c = Company.create_or_find_by!(name: '宮下酒造', kana: 'みやしたしゅぞう', prefecture_code: 33, city: '岡山市', address: '西川原184', tel: '086-272-5594', fax: '086-273-9243', website: 'http://www.msb.co.jp')
Brand.find_or_create_by!(name: '極聖', kana: 'きわみひじり', company: c)
c = Company.create_or_find_by!(name: '小林本店', kana: 'こばやしほんてん', prefecture_code: 33, city: '岡山市東区', address: '長沼833-1', tel: '086-942-5561', fax: '086-943-6456', website: '')
Brand.find_or_create_by!(name: '天来', kana: 'てんらい', company: c)
c = Company.create_or_find_by!(name: '玉泉酒造', kana: 'たまいずみしゅぞう', prefecture_code: 33, city: '備前市', address: '東片上312', tel: '0869-64-2008', fax: '0869-64-2039', website: 'http://www11.ocn.ne.jp/~tamano')
Brand.find_or_create_by!(name: '備前', kana: 'びぜん', company: c)
Brand.find_or_create_by!(name: '玉泉', kana: 'たまいずみ', company: c)
c = Company.create_or_find_by!(name: '藤原酒造', kana: 'ふじわらしゅぞう', prefecture_code: 33, city: '玉野市', address: '八浜町八浜843', tel: '0863-51-2014', fax: '0863-51-2676', website: '')
Brand.find_or_create_by!(name: '亀乃井', kana: 'かめのい', company: c)
c = Company.create_or_find_by!(name: '東郷酒造', kana: 'とうごうしゅぞう', prefecture_code: 33, city: '美作市', address: '巨勢1686', tel: '0868-72-1338', fax: '0868-72-1339', website: '')
Brand.find_or_create_by!(name: '東郷', kana: 'とうごう', company: c)
c = Company.create_or_find_by!(name: '田中酒造場', kana: 'たなかしゅぞうじょう', prefecture_code: 33, city: '美作市', address: '古町1655', tel: '0868-78-2059', fax: '0868-78-3378', website: 'http://www.musashi-sake.com')
Brand.find_or_create_by!(name: '白梅', kana: 'しらうめ', company: c)
Brand.find_or_create_by!(name: '武蔵の里', kana: 'むさしのさと', company: c)
Brand.find_or_create_by!(name: '宙狐', kana: 'ちゅうこ', company: c)
c = Company.create_or_find_by!(name: '後藤酒造', kana: 'ごとうしゅぞう', prefecture_code: 33, city: '苫田郡', address: '鏡野町香々美457', tel: '0868-56-0301', fax: '0868-56-0113', website: '')
Brand.find_or_create_by!(name: '舌鼓', kana: 'したつづみ', company: c)
Brand.find_or_create_by!(name: '藤娘', kana: 'ふじむすめ', company: c)
c = Company.create_or_find_by!(name: '牧野酒造本店', kana: 'まきのしゅぞうほんてん', prefecture_code: 33, city: '苫田郡', address: '鏡野町寺元425-1', tel: '0868-54-3881', fax: '0868-54-3883', website: 'http://makinosyuzo.web.fc2.com')
Brand.find_or_create_by!(name: '五十鈴', kana: 'いすず', company: c)
c = Company.create_or_find_by!(name: '難波酒造', kana: 'なんばしゅぞう', prefecture_code: 33, city: '津山市', address: '一宮436', tel: '0868-27-0008', fax: '0868-27-0234', website: 'http://musashi-sake.jp')
Brand.find_or_create_by!(name: '津山城', kana: 'つやまじょう', company: c)
Brand.find_or_create_by!(name: '富久迎', kana: 'ふくむかえ', company: c)
Brand.find_or_create_by!(name: '和心', kana: 'わしん', company: c)
Brand.find_or_create_by!(name: '作州武蔵', kana: 'さくしゅうむさし', company: c)
c = Company.create_or_find_by!(name: '苅田酒造エネルギー', kana: 'かんだしゅぞうえねるぎー', prefecture_code: 33, city: '津山市', address: '勝間田町17', tel: '0868-22-2018', fax: '0868-22-2188', website: '')
Brand.find_or_create_by!(name: '諸白', kana: 'もろはく', company: c)
c = Company.create_or_find_by!(name: '多胡本家酒造場', kana: 'たごほんけしゅぞうじょう', prefecture_code: 33, city: '津山市', address: '楢69', tel: '0868-29-1111', fax: '0868-29-1140', website: 'http://www.tsuyamabeer.co.jp')
Brand.find_or_create_by!(name: '加茂五葉', kana: 'かもいつは', company: c)
c = Company.create_or_find_by!(name: '金剛酒造', kana: 'こんごうしゅぞう', prefecture_code: 33, city: '和気郡', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '二人静', kana: 'ふたりしずか', company: c)
Brand.find_or_create_by!(name: '金剛', kana: 'こんごう', company: c)
c = Company.create_or_find_by!(name: '赤磐酒造', kana: 'あかいわしゅぞう', prefecture_code: 33, city: '赤磐市', address: '河本1113', tel: '086-955-0130', fax: '086-955-0762', website: 'http://www.akaiwa.co.jp')
Brand.find_or_create_by!(name: '桃の里', kana: 'もものさと', company: c)
c = Company.create_or_find_by!(name: '室町酒造', kana: 'むろまちしゅぞう', prefecture_code: 33, city: '赤磐市', address: '西中1342-1', tel: '086-955-0029', fax: '086-955-6887', website: 'http://www.sakuramuromachi.co.jp')
Brand.find_or_create_by!(name: '櫻室町', kana: 'さくらむろまち', company: c)
Brand.find_or_create_by!(name: '左近', kana: 'さこん', company: c)
c = Company.create_or_find_by!(name: '旭鶴酒造', kana: 'あさひつるしゅぞう', prefecture_code: 33, city: '久米郡', address: '久米南町上神目474-1', tel: '08672-2-1212', fax: '', website: '')
Brand.find_or_create_by!(name: '旭鶴', kana: 'あさひつる', company: c)
c = Company.create_or_find_by!(name: '森田酒造', kana: 'もりたしゅぞう', prefecture_code: 33, city: '倉敷市', address: '本町8-8', tel: '086-422-0252', fax: '086-424-0088', website: 'http://www.moritasyuzou.co.jp')
Brand.find_or_create_by!(name: '萬年雪', kana: 'まんねんゆき', company: c)
c = Company.create_or_find_by!(name: '熊屋酒造', kana: 'くまやしゅぞう', prefecture_code: 33, city: '倉敷市', address: '林705', tel: '086-485-0007', fax: '086-485-0465', website: 'https://www.facebook.com/ishichicom')
Brand.find_or_create_by!(name: '伊七', kana: 'いしち', company: c)
Brand.find_or_create_by!(name: '庵', kana: 'あん', company: c)
Brand.find_or_create_by!(name: 'HARE', kana: 'はれ', company: c)
Brand.find_or_create_by!(name: '巴福正宗', kana: 'ともえふくまさむね', company: c)
c = Company.create_or_find_by!(name: '白神酒造', kana: 'しらがしゅぞう', prefecture_code: 33, city: '倉敷市', address: '福井358', tel: '086-422-0090', fax: '086-422-3949', website: '')
Brand.find_or_create_by!(name: '玉司', kana: 'たまつかさ', company: c)
c = Company.create_or_find_by!(name: '十八盛酒造', kana: 'じゅうはちざかりしゅぞう', prefecture_code: 33, city: '倉敷市', address: '児島田の口5-6-14', tel: '086-477-7125', fax: '086-477-6518', website: 'http://www.juhachi.jp')
Brand.find_or_create_by!(name: '十八盛', kana: 'じゅうはちざかり', company: c)
Brand.find_or_create_by!(name: 'ことのわ', kana: 'ことのわ', company: c)
Brand.find_or_create_by!(name: '多賀治', kana: 'たがじ', company: c)
c = Company.create_or_find_by!(name: '三冠酒造', kana: 'さんかんしゅぞう', prefecture_code: 33, city: '倉敷市', address: '児島下の町2-9-22', tel: '086-472-3010', fax: '086-473-7252', website: 'http://www.sankan.co.jp')
Brand.find_or_create_by!(name: '和井田', kana: 'わいた', company: c)
Brand.find_or_create_by!(name: '三冠', kana: 'さんかん', company: c)
c = Company.create_or_find_by!(name: '大野酒造', kana: 'おおのしゅぞう', prefecture_code: 33, city: '倉敷市', address: '連島町西之浦3821', tel: '086-444-8022', fax: '086-444-8048', website: '')
Brand.find_or_create_by!(name: '富志美盛', kana: 'ふしみざかり', company: c)
c = Company.create_or_find_by!(name: '遠藤酒造場', kana: 'えんどうしゅぞうじょう', prefecture_code: 33, city: '倉敷市', address: '連島町西之浦2787', tel: '086-444-8005', fax: '086-444-8127', website: '')
Brand.find_or_create_by!(name: '宝富士', kana: 'たからふじ', company: c)
c = Company.create_or_find_by!(name: '渡辺酒造本店', kana: 'わたなべしゅぞうほんてん', prefecture_code: 33, city: '倉敷市', address: '連島町亀島新田170', tel: '086-444-8045', fax: '086-444-8043', website: 'http://www.minenohomare.com')
Brand.find_or_create_by!(name: '夢倉敷', kana: 'ゆめくらしき', company: c)
Brand.find_or_create_by!(name: '嶺乃誉', kana: 'みねのほまれ', company: c)
Brand.find_or_create_by!(name: '千歳楽', kana: 'せんざいらく', company: c)
c = Company.create_or_find_by!(name: '中田酒造', kana: 'なかたしゅぞう', prefecture_code: 33, city: '倉敷市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '歓びの泉', kana: 'よろこびのいずみ', company: c)
c = Company.create_or_find_by!(name: '三千鶴酒造', kana: 'みちつるしゅぞう', prefecture_code: 33, city: '倉敷市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '三千鶴', kana: 'みちつる', company: c)
c = Company.create_or_find_by!(name: '菊池酒造', kana: 'きくちしゅぞう', prefecture_code: 33, city: '倉敷市', address: '玉島阿賀崎1212', tel: '086-522-5145', fax: '086-522-5146', website: 'http://www.kikuchishuzo.co.jp')
Brand.find_or_create_by!(name: '燦然', kana: 'さんぜん', company: c)
c = Company.create_or_find_by!(name: '不二菊酒造本店', kana: 'ふじぎくしゅぞうほんてん', prefecture_code: 33, city: '倉敷市', address: '玉島黒崎8757-1', tel: '086-528-1052', fax: '086-528-0656', website: '')
Brand.find_or_create_by!(name: '不二菊', kana: 'ふじぎく', company: c)
c = Company.create_or_find_by!(name: '酔宝酒造', kana: 'すいほうしゅぞう', prefecture_code: 33, city: '倉敷市', address: '玉島黒崎7985', tel: '086-528-1111', fax: '086-528-1112', website: 'http://www.optic.or.jp/com/suiho/suiho.html')
Brand.find_or_create_by!(name: '酔寶', kana: 'すいほう', company: c)
c = Company.create_or_find_by!(name: '大内酒造場', kana: 'おおうちしゅぞうじょう', prefecture_code: 33, city: '笠岡市', address: '西大島7496', tel: '0865-67-0828', fax: '0865-67-0678', website: 'http://homepage1.nifty.com/ohuchi')
Brand.find_or_create_by!(name: '御嶽鶴', kana: 'みたけつる', company: c)
c = Company.create_or_find_by!(name: '嘉美心酒造', kana: 'かみこころしゅぞう', prefecture_code: 33, city: '浅口市', address: '寄島町7500-2', tel: '0865-54-3101', fax: '0865-54-3105', website: 'https://kamikokoro.co.jp')
Brand.find_or_create_by!(name: '真夏の果実', kana: 'まなつのかじつ', company: c)
Brand.find_or_create_by!(name: '神心', kana: 'かみこころ', company: c)
Brand.find_or_create_by!(name: '備中流', kana: 'びっちゅうりゅう', company: c)
Brand.find_or_create_by!(name: 'しゅわしゅわ', kana: 'しゅわしゅわ', company: c)
Brand.find_or_create_by!(name: '嘉美心', kana: 'かみこころ', company: c)
Brand.find_or_create_by!(name: '冬の月', kana: 'ふゆのつき', company: c)
c = Company.create_or_find_by!(name: '山成酒造', kana: 'やまなりしゅぞう', prefecture_code: 33, city: '井原市', address: '芳井町簗瀬23', tel: '0866-72-0001', fax: '0866-72-0010', website: 'http://yamanari.jp')
Brand.find_or_create_by!(name: '蘭の誉', kana: 'らんのほまれ', company: c)
c = Company.create_or_find_by!(name: '瀧本酒造', kana: 'たきもとしゅぞう', prefecture_code: 33, city: '井原市', address: '井原町1050-2', tel: '0866-62-0026', fax: '0866-62-0126', website: 'http://www.瀧本酒造.com')
Brand.find_or_create_by!(name: '一品', kana: 'いっぴん', company: c)
c = Company.create_or_find_by!(name: '白菊酒造', kana: 'しらぎくしゅぞう', prefecture_code: 33, city: '高梁市', address: '成羽町下日名163-1', tel: '0866-42-3132', fax: '0866-42-2165', website: 'https://www.shiragiku.com')
Brand.find_or_create_by!(name: '大典白菊', kana: 'たいてんしらぎく', company: c)
Brand.find_or_create_by!(name: '備州', kana: 'びしゅう', company: c)
c = Company.create_or_find_by!(name: '赤木酒造', kana: 'あかぎしゅぞう', prefecture_code: 33, city: '高梁市', address: '備中町長屋43', tel: '0866-45-3006', fax: '0866-45-3789', website: '')
Brand.find_or_create_by!(name: '蘭亭曲水', kana: 'らんていきょくすい', company: c)
c = Company.create_or_find_by!(name: '小出酒造', kana: 'こいでしゅぞう', prefecture_code: 33, city: '加賀郡', address: '吉備中央町納地111-2', tel: '0866-54-1436', fax: '0866-54-0436', website: '')
Brand.find_or_create_by!(name: '高雪', kana: 'たかゆき', company: c)
c = Company.create_or_find_by!(name: '芳烈酒造', kana: 'ほうれつしゅぞう', prefecture_code: 33, city: '高梁市', address: '有漢町有漢2535-1', tel: '0866-57-2003', fax: '0866-57-2003', website: 'http://www.houretu.jp')
Brand.find_or_create_by!(name: '櫻芳烈', kana: 'おうほうれつ', company: c)
c = Company.create_or_find_by!(name: '落酒造場', kana: 'おちしゅぞうじょう', prefecture_code: 33, city: '真庭市', address: '下呰部664-4', tel: '0866-52-2311', fax: '0866-52-4495', website: 'http://taishonotsuru.com')
Brand.find_or_create_by!(name: '落花流水', kana: 'らっかりゅうすい', company: c)
Brand.find_or_create_by!(name: '大正の鶴', kana: 'たいしょうのつる', company: c)
c = Company.create_or_find_by!(name: '辻本店', kana: 'つじほんてん', prefecture_code: 33, city: '真庭市', address: '勝山116', tel: '0867-44-3155', fax: '0867-44-5290', website: 'https://www.gozenshu.co.jp')
Brand.find_or_create_by!(name: '炭屋彌兵衛', kana: 'すみややへい', company: c)
Brand.find_or_create_by!(name: '御前酒', kana: 'ごぜんしゅ', company: c)
c = Company.create_or_find_by!(name: '大美酒造', kana: 'おおみしゅぞう', prefecture_code: 33, city: '真庭市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '美保鶴', kana: 'みほつる', company: c)
c = Company.create_or_find_by!(name: '神露酒造', kana: 'しんろしゅぞう', prefecture_code: 33, city: '浅口市', address: '金光町大谷227', tel: '0865-42-2015', fax: '0865-42-5983', website: 'http://www.sinro.co.jp')
Brand.find_or_create_by!(name: '神露', kana: 'しんろ', company: c)
c = Company.create_or_find_by!(name: '丸本酒造', kana: 'まるもとしゅぞう', prefecture_code: 33, city: '浅口市', address: '鴨方町本庄2485', tel: '0865-44-3155', fax: '0865-44-3156', website: 'http://kamomidori.co.jp')
Brand.find_or_create_by!(name: '泡々酒', kana: 'ほうほうしゅ', company: c)
Brand.find_or_create_by!(name: '竹林', kana: 'ちくりん', company: c)
Brand.find_or_create_by!(name: 'かもみどり', kana: 'かもみどり', company: c)
Brand.find_or_create_by!(name: 'EARTH SCIENCE', kana: 'アース サイエンス', company: c)
c = Company.create_or_find_by!(name: '平喜酒造', kana: 'ひらきしゅぞう', prefecture_code: 33, city: '浅口市', address: '鴨方町鴨方1283', tel: '0865-44-2122', fax: '0865-44-2863', website: 'http://www.hirakishuzo.co.jp')
Brand.find_or_create_by!(name: '鯨正宗', kana: 'くじらまさむね', company: c)
Brand.find_or_create_by!(name: '喜平', kana: 'きへい', company: c)
Brand.find_or_create_by!(name: '将軍', kana: 'しょうぐん', company: c)
Brand.find_or_create_by!(name: '新婚', kana: 'しんこん', company: c)
Brand.find_or_create_by!(name: '正義櫻', kana: 'せいぎざくら', company: c)
c = Company.create_or_find_by!(name: '藤田酒造', kana: 'ふじたしゅぞう', prefecture_code: 33, city: '浅口市', address: '鴨方町鴨方152-2', tel: '0865-44-2016', fax: '0865-44-9868', website: '')
Brand.find_or_create_by!(name: '金光賀眞', kana: 'こんこうかしん', company: c)
c = Company.create_or_find_by!(name: '磯千鳥酒造', kana: 'いそちどりしゅぞう', prefecture_code: 33, city: '浅口郡', address: '里庄町新庄306', tel: '0865-64-3456', fax: '0865-64-4336', website: 'http://www.isochidori.co.jp')
Brand.find_or_create_by!(name: '磯千鳥', kana: 'いそちどり', company: c)
c = Company.create_or_find_by!(name: '松永酒造', kana: 'まつながしゅぞう', prefecture_code: 33, city: '総社市', address: '真壁541', tel: '0866-92-0174', fax: '020-4665-5416', website: '')
Brand.find_or_create_by!(name: '常磐鶴', kana: 'ときわつる', company: c)
Brand.find_or_create_by!(name: '吉備路', kana: 'きびじ', company: c)
Brand.find_or_create_by!(name: 'かみよ 赤米の酒', kana: 'かみよ あかまいのさけ', company: c)
c = Company.create_or_find_by!(name: '三宅酒造', kana: 'みやけしゅぞう', prefecture_code: 33, city: '総社市', address: '宿355', tel: '0866-92-0075', fax: '0866-92-0075', website: 'http://suifu-miyake.jp')
Brand.find_or_create_by!(name: '粹府', kana: 'すいふ', company: c)
c = Company.create_or_find_by!(name: 'ヨイキゲン', kana: 'よいきげん', prefecture_code: 33, city: '総社市', address: '清音上中島372-1', tel: '0866-94-0011', fax: '0866-94-4052', website: 'http://www.yoikigen.co.jp')
Brand.find_or_create_by!(name: 'れんげの舞い', kana: 'れんげのまい', company: c)
Brand.find_or_create_by!(name: '酔機嫌', kana: 'よいきげん', company: c)
Brand.find_or_create_by!(name: '碧天', kana: 'へきてん', company: c)
c = Company.create_or_find_by!(name: '三光正宗', kana: 'さんこうまさむね', prefecture_code: 33, city: '新見市', address: '哲西町上神代951', tel: '0867-94-3131', fax: '0867-94-3200', website: 'http://www.sake-sanko.co.jp')
Brand.find_or_create_by!(name: '蛇形', kana: 'じゃがた', company: c)
Brand.find_or_create_by!(name: '三光洸雲', kana: 'さんこうこううん', company: c)
Brand.find_or_create_by!(name: '三光天賦', kana: 'さんこうてんぷ', company: c)
Brand.find_or_create_by!(name: '三光正宗', kana: 'さんこうまさむね', company: c)
Brand.find_or_create_by!(name: '克正', kana: 'かつまさ', company: c)
