c = Company.create_or_find_by!(name: '岡酒造', kana: 'おかしゅぞう', prefecture_code: 38, city: '松山市', address: '萱町5-10-2', tel: '089-925-3841', fax: '089-925-7034', website: '')
Brand.find_or_create_by!(name: 'かちとき', kana: 'かちとき', company: c)
c = Company.create_or_find_by!(name: '愛媛県酒造共同組合', kana: 'えひめけんしゅぞうきょうどうくみあい', prefecture_code: 38, city: '松山市', address: '道後湯之町10-7', tel: '089-913-8030', fax: '089-913-1371', website: 'http://www.ehime-syuzou.com')
Brand.find_or_create_by!(name: '媛の愛', kana: 'ひめのあい', company: c)
c = Company.create_or_find_by!(name: '水口酒造', kana: 'みなくちしゅぞう', prefecture_code: 38, city: '松山市', address: '道後喜多町3-23', tel: '089-924-6616', fax: '089-924-3707', website: 'https://www.dogobeer.co.jp')
Brand.find_or_create_by!(name: '仁喜多津', kana: 'にきたつ', company: c)
Brand.find_or_create_by!(name: '道後蔵酒', kana: 'どうごくらざけ', company: c)
c = Company.create_or_find_by!(name: '後藤酒造', kana: 'ごとうしゅぞう', prefecture_code: 38, city: '松山市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '久米の井', kana: 'くめのい', company: c)
Brand.find_or_create_by!(name: '十五万石', kana: 'じゅうごまんごく', company: c)
Brand.find_or_create_by!(name: '眞十郎', kana: 'しんじゅうろう', company: c)
c = Company.create_or_find_by!(name: '栄光酒造', kana: 'えいこうしゅぞう', prefecture_code: 38, city: '松山市', address: '溝辺町甲443', tel: '089-977-0964', fax: '089-977-5413', website: 'http://www.eikoo.com')
Brand.find_or_create_by!(name: '栄光', kana: 'えいこう', company: c)
c = Company.create_or_find_by!(name: '横河酒造', kana: 'よこかわしゅぞう', prefecture_code: 38, city: '東温市', address: '横河原1304-1', tel: '089-964-2116', fax: '089-964-2116', website: '')
Brand.find_or_create_by!(name: '男花', kana: 'おとこはな', company: c)
c = Company.create_or_find_by!(name: '島田酒造', kana: 'しまだしゅぞう', prefecture_code: 38, city: '東温市', address: '志津川1445', tel: '089-964-2111', fax: '089-964-2129', website: '')
Brand.find_or_create_by!(name: '小富士', kana: 'こふじ', company: c)
c = Company.create_or_find_by!(name: 'お茂ご酒造', kana: 'おもごしゅぞう', prefecture_code: 38, city: '上浮穴郡', address: '久万高原町久万137', tel: '0892-21-0025', fax: '0892-21-1525', website: 'http://www.omogo.jp')
Brand.find_or_create_by!(name: 'お茂ご', kana: 'おもご', company: c)
c = Company.create_or_find_by!(name: '雪娘酒造', kana: 'ゆきむすめしゅぞう', prefecture_code: 38, city: '上浮穴郡', address: '久万高原町久万327', tel: '0892-21-0007', fax: '0892-21-0747', website: '')
Brand.find_or_create_by!(name: '雪娘', kana: 'ゆきむすめ', company: c)
c = Company.create_or_find_by!(name: 'かち鶴酒造', kana: 'かちづるしゅぞう', prefecture_code: 38, city: '伊予郡', address: '砥部町宮内542', tel: '089-962-2017', fax: '089-962-7591', website: 'http://www.kachizuru.com')
Brand.find_or_create_by!(name: 'かち鶴', kana: 'かちづる', company: c)
c = Company.create_or_find_by!(name: '協和酒造', kana: 'きょうわしゅぞう', prefecture_code: 38, city: '伊予郡', address: '砥部町大南400', tel: '089-962-2717', fax: '089-962-7788', website: 'https://www.hatsuyukihai.jp')
Brand.find_or_create_by!(name: '初雪盃', kana: 'はつゆきはい', company: c)
c = Company.create_or_find_by!(name: '佐々木酒造', kana: 'ささきしゅぞう', prefecture_code: 38, city: '伊予郡', address: '砥部町総津785', tel: '089-969-2005', fax: '089-969-2605', website: '')
Brand.find_or_create_by!(name: '八重菊', kana: 'やえぎく', company: c)
c = Company.create_or_find_by!(name: '武智酒店', kana: 'たけちさけみせ', prefecture_code: 38, city: '伊予郡', address: '松前町北黒田816', tel: '089-984-1037', fax: '089-984-1037', website: '')
Brand.find_or_create_by!(name: '武士心', kana: 'ぶしごころ', company: c)
c = Company.create_or_find_by!(name: '酒六酒造', kana: 'さかろくしゅぞう', prefecture_code: 38, city: '喜多郡', address: '内子町内子3279-1', tel: '0893-44-3054', fax: '0893-44-3140', website: 'http://www.sakaroku-syuzo.co.jp')
Brand.find_or_create_by!(name: '内子座', kana: 'うちこざ', company: c)
Brand.find_or_create_by!(name: '一刀両断', kana: 'いっとうりょうだん', company: c)
Brand.find_or_create_by!(name: '七星剣', kana: 'しちせいけん', company: c)
Brand.find_or_create_by!(name: '京ひな', kana: 'きょうひな', company: c)
Brand.find_or_create_by!(name: '隠し剣', kana: 'かくしけん', company: c)
Brand.find_or_create_by!(name: '吹毛剣', kana: 'すいもうけん', company: c)
Brand.find_or_create_by!(name: 'mar 京ひな', kana: 'まーる', company: c)
c = Company.create_or_find_by!(name: '近藤酒造', kana: 'こんどうしゅぞう', prefecture_code: 38, city: '新居浜市', address: '新須賀町1-11-46', tel: '0897-33-1177', fax: '0897-37-3351', website: 'http://www.kondousyuzou.com')
Brand.find_or_create_by!(name: '群青', kana: 'ぐんじょう', company: c)
Brand.find_or_create_by!(name: '銅山こそあなた', kana: 'たからこそあなた', company: c)
Brand.find_or_create_by!(name: '華姫桜', kana: 'はなひめさくら', company: c)
c = Company.create_or_find_by!(name: '蔵本屋本店', kana: 'くらもとやほんてん', prefecture_code: 38, city: '西条市', address: '氷見乙1785', tel: '0897-57-9900', fax: '', website: '')
Brand.find_or_create_by!(name: '行光', kana: 'ゆきみつ', company: c)
c = Company.create_or_find_by!(name: '石鎚酒造', kana: 'いしづちしゅぞう', prefecture_code: 38, city: '西条市', address: '氷見丙402-3', tel: '0897-57-8000', fax: '0897-57-8811', website: 'https://www.ishizuchi.co.jp')
Brand.find_or_create_by!(name: '石鎚', kana: 'いしづち', company: c)
c = Company.create_or_find_by!(name: '八木酒造部', kana: 'やぎしゅぞうぶ', prefecture_code: 38, city: '今治市', address: '旭町3-3-8', tel: '0898-22-6700', fax: '0898-33-0276', website: 'http://www.yamatan.jp')
Brand.find_or_create_by!(name: '山丹正宗', kana: 'やまたんまさむね', company: c)
c = Company.create_or_find_by!(name: '後藤酒造', kana: 'ごとうしゅぞう', prefecture_code: 38, city: '大洲市', address: '八多喜町100', tel: '0893-26-0009', fax: '0893-26-1155', website: '')
Brand.find_or_create_by!(name: 'きた美人', kana: 'きたびじん', company: c)
c = Company.create_or_find_by!(name: '千代の亀酒造', kana: 'ちよのかめしゅぞう', prefecture_code: 38, city: '喜多郡', address: '内子町平岡甲1294番地', tel: '0893-44-2201', fax: '0893-43-1036', website: 'http://www.chiyonokame.com')
Brand.find_or_create_by!(name: '千代の亀', kana: 'ちよのかめ', company: c)
Brand.find_or_create_by!(name: '媛人 A/END', kana: 'えんど', company: c)
Brand.find_or_create_by!(name: 'mar 千代の亀', kana: 'まーる', company: c)
c = Company.create_or_find_by!(name: '梅美人酒造', kana: 'うめびじんしゅぞう', prefecture_code: 38, city: '八幡浜市', address: '1557-2', tel: '0894-22-0312', fax: '0894-22-0712', website: 'https://umebijin.com')
Brand.find_or_create_by!(name: '梅美人', kana: 'うめびじん', company: c)
Brand.find_or_create_by!(name: '鷹雄', kana: 'たかお', company: c)
c = Company.create_or_find_by!(name: '桐万長酒造', kana: 'きりまんちょうしゅぞう', prefecture_code: 38, city: '八幡浜市', address: '保内町川之石3-11-3', tel: '0894-36-0146', fax: '0894-36-1231', website: '')
Brand.find_or_create_by!(name: '桐万長', kana: 'きりまんちょう', company: c)
c = Company.create_or_find_by!(name: '松田酒造', kana: 'まつだしゅぞう', prefecture_code: 38, city: '西宇和郡', address: '伊方町湊浦1003-2', tel: '0894-38-1111', fax: '0894-38-1110', website: '')
Brand.find_or_create_by!(name: '佐田岬', kana: 'さだみさき', company: c)
Brand.find_or_create_by!(name: '宮乃舞', kana: 'みやのまい', company: c)
c = Company.create_or_find_by!(name: '小泉酒造', kana: 'こいずみしゅぞう', prefecture_code: 38, city: '八幡浜市', address: '広瀬2-4-10', tel: '0894-22-0170', fax: '', website: '')
Brand.find_or_create_by!(name: '鯉の勢', kana: 'こいのせ', company: c)
c = Company.create_or_find_by!(name: '川亀酒造', kana: 'かわかめしゅぞう', prefecture_code: 38, city: '八幡浜市', address: '五反田2-4-1', tel: '0894-22-0315', fax: '0894-22-0953', website: '')
Brand.find_or_create_by!(name: '川亀', kana: 'かわかめ', company: c)
c = Company.create_or_find_by!(name: '元見屋酒店', kana: 'もとみやさけてん', prefecture_code: 38, city: '西予市', address: '宇和町卯之町3-88', tel: '0894-62-0036', fax: '0894-62-5656', website: 'http://www.motomiya.jp')
Brand.find_or_create_by!(name: '開明', kana: 'かいめい', company: c)
c = Company.create_or_find_by!(name: '宇都宮酒造', kana: 'うつのみやしゅぞう', prefecture_code: 38, city: '西予市', address: '宇和町卯之町4-254', tel: '0894-62-0117', fax: '0894-62-0117', website: '')
Brand.find_or_create_by!(name: '千鳥', kana: 'ちどり', company: c)
Brand.find_or_create_by!(name: '花神', kana: 'かしん', company: c)
c = Company.create_or_find_by!(name: '最進酒造', kana: 'さいしんしゅぞう', prefecture_code: 38, city: '西予市', address: '宇和町卯之町4-332', tel: '0894-62-0223', fax: '0894-62-0396', website: 'http://www9.ocn.ne.jp/~ikedaya')
Brand.find_or_create_by!(name: '玉川', kana: 'たまがわ', company: c)
c = Company.create_or_find_by!(name: '緒方酒造', kana: 'おがたしゅぞう', prefecture_code: 38, city: '西予市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '緒方洪庵', kana: 'おがたこうあん', company: c)
Brand.find_or_create_by!(name: '児島惟謙', kana: 'こじまこれかた', company: c)
Brand.find_or_create_by!(name: '緒方惟貞', kana: 'おがたこれさだ', company: c)
Brand.find_or_create_by!(name: '東洋', kana: 'とうよう', company: c)
c = Company.create_or_find_by!(name: '養老酒造', kana: 'ようろうしゅぞう', prefecture_code: 38, city: '大洲市', address: '肱川町山鳥坂49', tel: '0893-34-2352', fax: '0893-34-2390', website: 'https://yoroshuzo.jp')
Brand.find_or_create_by!(name: '風の里', kana: 'かぜのさと', company: c)
Brand.find_or_create_by!(name: '共', kana: 'とも', company: c)
Brand.find_or_create_by!(name: '歌麿', kana: 'うたまろ', company: c)
Brand.find_or_create_by!(name: '鵜洲', kana: 'うしゅう', company: c)
Brand.find_or_create_by!(name: '叶川', kana: 'かのがわ', company: c)
Brand.find_or_create_by!(name: '養老', kana: 'ようろう', company: c)
c = Company.create_or_find_by!(name: '中城本家酒造', kana: 'なかしろほんけしゅぞう', prefecture_code: 38, city: '西予市', address: '城川町嘉喜尾1319', tel: '0894-82-0146', fax: '0894-82-0074', website: '')
Brand.find_or_create_by!(name: '城川郷', kana: 'しろかわごう', company: c)
c = Company.create_or_find_by!(name: '名門サカイ', kana: 'めいもんさかい', prefecture_code: 38, city: '宇和島市', address: '高串2-1045', tel: '0895-25-5533', fax: '0895-25-5535', website: 'http://www.meimon.co.jp')
Brand.find_or_create_by!(name: '名門', kana: 'めいもん', company: c)
c = Company.create_or_find_by!(name: '西本酒造', kana: 'にしもとしゅぞう', prefecture_code: 38, city: '宇和島市', address: '三間町宮野下855', tel: '0895-58-2008', fax: '0895-58-2018', website: 'http://toranoo.com')
Brand.find_or_create_by!(name: '虎の尾', kana: 'とらのお', company: c)
Brand.find_or_create_by!(name: '大番', kana: 'おおばん', company: c)
c = Company.create_or_find_by!(name: '正木正光酒造場', kana: 'まさきまさみつしゅぞうじょう', prefecture_code: 38, city: '北宇和郡', address: '松野町松丸178', tel: '0895-42-1128', fax: '0895-42-1129', website: '')
Brand.find_or_create_by!(name: '野武士', kana: 'のぶし', company: c)
c = Company.create_or_find_by!(name: '赤松本家酒造', kana: 'あかまつほんけしゅぞう', prefecture_code: 38, city: '宇和島市', address: '津島町上畑地甲1502', tel: '0895-32-2727', fax: '0895-32-6216', website: '')
Brand.find_or_create_by!(name: '泰山', kana: 'たいざん', company: c)
c = Company.create_or_find_by!(name: '小西酒造場', kana: 'こにししゅぞうじょう', prefecture_code: 38, city: '南宇和郡', address: '愛南町蓮乗寺3', tel: '0895-72-0019', fax: '0895-72-0019', website: '')
Brand.find_or_create_by!(name: '誠心', kana: 'せいしん', company: c)
c = Company.create_or_find_by!(name: '今村酒造', kana: 'いまむらしゅぞう', prefecture_code: 38, city: '四国中央市', address: '上分町742-2', tel: '0896-58-3011', fax: '0896-58-1939', website: '')
Brand.find_or_create_by!(name: '豊稔', kana: 'ほうねん', company: c)
c = Company.create_or_find_by!(name: '梅錦山川', kana: 'うめにしきやまかわ', prefecture_code: 38, city: '四国中央市', address: '金田町金川14', tel: '0896-58-1211', fax: '0896-58-3171', website: 'https://www.umenishiki.com')
Brand.find_or_create_by!(name: '山川流', kana: 'やまかわりゅう', company: c)
Brand.find_or_create_by!(name: '酒屋の女房の盗み酒', kana: 'さかやのにょうぼうのぬすみざけ', company: c)
Brand.find_or_create_by!(name: '梅錦', kana: 'うめにしき', company: c)
c = Company.create_or_find_by!(name: '篠永酒造', kana: 'しのながしゅぞう', prefecture_code: 38, city: '四国中央市', address: '', tel: '', fax: '', website: '')
CompanyStatusHistory.create!(company: c, event_type: :status_change, business_status: :closed)
Brand.find_or_create_by!(name: '森の翠', kana: 'もりのみどり', company: c)
c = Company.create_or_find_by!(name: '首藤酒造', kana: 'すとうしゅぞう', prefecture_code: 38, city: '西条市', address: '小松町大頭甲312-2', tel: '0898-72-2720', fax: '0898-72-3918', website: 'http://sukigokoro.co.jp')
Brand.find_or_create_by!(name: '寿喜心', kana: 'すきごころ', company: c)
c = Company.create_or_find_by!(name: '武田酒造', kana: 'たけだしゅぞう', prefecture_code: 38, city: '西条市', address: '三芳1507', tel: '0898-66-5002', fax: '0898-66-2577', website: 'http://www.yamatogokoro.co.jp')
Brand.find_or_create_by!(name: '媛一会', kana: 'ひめいちえ', company: c)
Brand.find_or_create_by!(name: '日本心', kana: 'やまとごころ', company: c)
c = Company.create_or_find_by!(name: '秋川酒造', kana: 'あきかわしゅぞう', prefecture_code: 38, city: '西条市', address: '大野150', tel: '0898-66-5014', fax: '0898-66-6470', website: 'http://www5b.biglobe.ne.jp/~sake')
Brand.find_or_create_by!(name: '御国鶴', kana: 'みくにつる', company: c)
c = Company.create_or_find_by!(name: '成龍酒造', kana: 'せいりょうしゅぞう', prefecture_code: 38, city: '西条市', address: '周布1301-1', tel: '0898-68-8566', fax: '0898-68-7103', website: 'http://www.seiryosyuzo.com')
Brand.find_or_create_by!(name: '御代栄', kana: 'みよさかえ', company: c)
Brand.find_or_create_by!(name: '賀儀屋', kana: 'かぎや', company: c)
Brand.find_or_create_by!(name: '成龍然', kana: 'せいりょうぜん', company: c)
Brand.find_or_create_by!(name: '宵待媛', kana: 'よいまちひめ', company: c)
c = Company.create_or_find_by!(name: '森松酒造場', kana: 'もりまつしゅぞうじょう', prefecture_code: 38, city: '今治市', address: '菊間町浜890-1', tel: '0898-54-2020', fax: '0898-54-2020', website: '')
Brand.find_or_create_by!(name: '菊間美人', kana: 'きくまびじん', company: c)
c = Company.create_or_find_by!(name: '桜うづまき酒造', kana: 'さくらうづまきしゅぞう', prefecture_code: 38, city: '松山市', address: '八反地71', tel: '089-992-1011', fax: '', website: 'http://www.sakurauzumaki.co.jp')
Brand.find_or_create_by!(name: '桜うづまき', kana: 'さくらうづまき', company: c)
c = Company.create_or_find_by!(name: '雪雀酒造', kana: 'ゆきすずめしゅぞう', prefecture_code: 38, city: '松山市', address: '柳原123', tel: '089-992-0025', fax: '089-993-0052', website: 'https://yukisuzume.com')
Brand.find_or_create_by!(name: 'mar 雪雀', kana: 'まーる', company: c)
Brand.find_or_create_by!(name: '雪雀', kana: 'ゆきすずめ', company: c)
Brand.find_or_create_by!(name: '雀正宗', kana: 'すずめまさむね', company: c)
c = Company.create_or_find_by!(name: '徳本酒造', kana: 'とくもとしゅぞう', prefecture_code: 38, city: '伊予市', address: '灘町12', tel: '089-982-0030', fax: '089-982-0975', website: '')
Brand.find_or_create_by!(name: '初鷹', kana: 'はつたか', company: c)
c = Company.create_or_find_by!(name: '奥嶋酒造', kana: 'おくしましゅぞう', prefecture_code: 38, city: '伊予市', address: '双海町上灘5711', tel: '089-986-0028', fax: '089-986-0064', website: '')
Brand.find_or_create_by!(name: '島錦', kana: 'しまにしき', company: c)
c = Company.create_or_find_by!(name: '濱田酒造', kana: 'はまだしゅぞう', prefecture_code: 38, city: '宇和島市', address: '吉田町法花津2-156', tel: '0895-52-1002', fax: '0895-52-1002', website: '')
Brand.find_or_create_by!(name: '寿', kana: 'ことぶき', company: c)
