c = Company.create_or_find_by!(name: '酔鯨酒造', kana: 'すいげいしゅぞう', prefecture_code: 39, city: '高知市', address: '長浜566-1', tel: '088-841-4080', fax: '088-856-8818', website: 'https://suigei.co.jp')
Brand.find_or_create_by!(name: '酔鯨', kana: 'すいげい', company: c)
Brand.find_or_create_by!(name: 'DAITO', kana: 'ダイト', company: c)
c = Company.create_or_find_by!(name: '亀泉酒造', kana: 'かめいずみしゅぞう', prefecture_code: 39, city: '土佐市', address: '出間2123-1', tel: '088-854-0811', fax: '088-854-0813', website: 'http://www.kameizumi.co.jp')
Brand.find_or_create_by!(name: '亀泉', kana: 'かめいずみ', company: c)
c = Company.create_or_find_by!(name: '高知酒造', kana: 'こうちしゅぞう', prefecture_code: 39, city: '吾川郡', address: 'いの町勝賀瀬780-2', tel: '088-897-0314', fax: '088-897-0315', website: 'http://kochi-sake.com')
Brand.find_or_create_by!(name: '瀧嵐', kana: 'たきあらし', company: c)
c = Company.create_or_find_by!(name: '土佐酒造', kana: 'とさしゅぞう', prefecture_code: 39, city: '土佐郡', address: '土佐町田井418', tel: '0887-82-0504', fax: '0887-82-1984', website: 'http://www.keigetsu.co.jp')
Brand.find_or_create_by!(name: '桂月', kana: 'けいげつ', company: c)
c = Company.create_or_find_by!(name: '高木酒造', kana: 'たかぎしゅぞう', prefecture_code: 39, city: '香南市', address: '赤岡町443', tel: '0887-55-1800', fax: '0887-55-2605', website: 'https://www.toyonoume.com')
Brand.find_or_create_by!(name: '空と海', kana: 'そらとうみ', company: c)
Brand.find_or_create_by!(name: '土佐金蔵', kana: 'とさきんぞう', company: c)
Brand.find_or_create_by!(name: '豊の梅', kana: 'とよのうめ', company: c)
Brand.find_or_create_by!(name: 'ALIENS', kana: 'エイリアンズ', company: c)
c = Company.create_or_find_by!(name: '仙頭酒造場', kana: 'せんとうしゅぞうじょう', prefecture_code: 39, city: '安芸郡', address: '芸西村和食甲1551', tel: '0887-33-2611', fax: '0887-33-2612', website: 'https://www.tosashiragiku.com')
Brand.find_or_create_by!(name: '土佐しらぎく', kana: 'とさしらぎく', company: c)
Brand.find_or_create_by!(name: '美潮', kana: 'みしお', company: c)
Brand.find_or_create_by!(name: '土佐深海', kana: 'とさしんかい', company: c)
c = Company.create_or_find_by!(name: '浜川商店', kana: 'はまかわしょうてん', prefecture_code: 39, city: '安芸郡', address: '田野町2150', tel: '0887-38-2004', fax: '0887-38-8284', website: 'http://bijofu.jp')
Brand.find_or_create_by!(name: '濱乃鶴', kana: 'はまのつる', company: c)
Brand.find_or_create_by!(name: '美丈夫', kana: 'びじょうふ', company: c)
Brand.find_or_create_by!(name: '慎太郎 SHINTARO', kana: 'しんたろう', company: c)
c = Company.create_or_find_by!(name: '南酒造場', kana: 'みなみしゅぞうじょう', prefecture_code: 39, city: '安芸郡', address: '安田町安田1875', tel: '0887-38-6811', fax: '0887-38-6812', website: '')
Brand.find_or_create_by!(name: '玉の井', kana: 'たまのい', company: c)
Brand.find_or_create_by!(name: '南', kana: 'みなみ', company: c)
c = Company.create_or_find_by!(name: '土佐鶴酒造', kana: 'とさつるしゅぞう', prefecture_code: 39, city: '安芸郡', address: '安田町安田1586', tel: '0887-38-6511', fax: '0887-38-3787', website: 'https://tosatsuru.co.jp')
Brand.find_or_create_by!(name: 'azure', kana: 'アジュール', company: c)
Brand.find_or_create_by!(name: '土佐鶴', kana: 'とさつる', company: c)
c = Company.create_or_find_by!(name: 'アリサワ', kana: 'ありさわ', prefecture_code: 39, city: '香美市', address: '土佐山田町西本町1-4-1', tel: '0887-52-3177', fax: '0887-52-4415', website: '')
Brand.find_or_create_by!(name: '鳴子舞', kana: 'なるこまい', company: c)
Brand.find_or_create_by!(name: '糀おしろい', kana: 'はなおしろい', company: c)
Brand.find_or_create_by!(name: '四万十旅情', kana: 'しまんとりょじょう', company: c)
Brand.find_or_create_by!(name: '鏡野', kana: 'かがみの', company: c)
Brand.find_or_create_by!(name: '土州魂', kana: 'どしゅうだましい', company: c)
Brand.find_or_create_by!(name: 'たいら', kana: 'たいら', company: c)
Brand.find_or_create_by!(name: '文佳人', kana: 'ぶんかじん', company: c)
c = Company.create_or_find_by!(name: '松尾酒造', kana: 'まつおしゅぞう', prefecture_code: 39, city: '香美市', address: '土佐山田町西本町5-1-1', tel: '0887-53-2273', fax: '0887-53-3990', website: '')
Brand.find_or_create_by!(name: '山田太鼓', kana: 'やまだだいこ', company: c)
Brand.find_or_create_by!(name: '松翁', kana: 'まつおきな', company: c)
c = Company.create_or_find_by!(name: '菊水酒造', kana: 'きくすいしゅぞう', prefecture_code: 39, city: '安芸市', address: '本町4-6-25', tel: '0887-35-3501', fax: '0887-35-3503', website: 'http://www.tosa-kikusui.co.jp')
Brand.find_or_create_by!(name: '土佐菊水', kana: 'とさきくすい', company: c)
Brand.find_or_create_by!(name: '四万十川', kana: 'しまんとがわ', company: c)
c = Company.create_or_find_by!(name: '有光酒造場', kana: 'ありみつしゅぞうじょう', prefecture_code: 39, city: '安芸市', address: '赤野甲38-1', tel: '0887-33-2117', fax: '0887-33-4477', website: 'http://ww8.tiki.ne.jp/~akano')
Brand.find_or_create_by!(name: '玉川', kana: 'たまがわ', company: c)
Brand.find_or_create_by!(name: '赤野', kana: 'あかの', company: c)
Brand.find_or_create_by!(name: '安芸虎', kana: 'あきとら', company: c)
c = Company.create_or_find_by!(name: '文本酒造', kana: 'ふみもとしゅぞう', prefecture_code: 39, city: '高岡郡', address: '四万十町本町4-23', tel: '0880-22-0039', fax: '0880-22-2670', website: '')
Brand.find_or_create_by!(name: '桃太郎', kana: 'ももたろう', company: c)
Brand.find_or_create_by!(name: '入駒', kana: 'いりこま', company: c)
Brand.find_or_create_by!(name: '四万十ノ', kana: 'しまんとの', company: c)
Brand.find_or_create_by!(name: '霧の里', kana: 'きりのさと', company: c)
c = Company.create_or_find_by!(name: '無手無冠', kana: 'むてむか', prefecture_code: 39, city: '高岡郡', address: '四万十町大正452', tel: '0880-27-0316', fax: '0880-27-0380', website: 'http://www.mutemuka.com')
Brand.find_or_create_by!(name: '無手無冠', kana: 'むてむか', company: c)
Brand.find_or_create_by!(name: '千代登', kana: 'ちよのぼり', company: c)
c = Company.create_or_find_by!(name: '藤娘酒造', kana: 'ふじむすめしゅぞう', prefecture_code: 39, city: '四万十市', address: '中村新町4-5', tel: '0880-34-4131', fax: '0880-34-4132', website: 'http://shimanto-fujimusume.com')
Brand.find_or_create_by!(name: 'とみやま', kana: 'とみやま', company: c)
Brand.find_or_create_by!(name: '宇宙の夢', kana: 'うちゅうのゆめ', company: c)
Brand.find_or_create_by!(name: '藤娘', kana: 'ふじむすめ', company: c)
c = Company.create_or_find_by!(name: '司牡丹酒造', kana: 'つかさぼたんしゅぞう', prefecture_code: 39, city: '高岡郡', address: '佐川町甲1299', tel: '0889-22-1211', fax: '0889-22-4116', website: 'https://www.tsukasabotan.co.jp')
Brand.find_or_create_by!(name: '花と恋して', kana: 'はなとこいして', company: c)
Brand.find_or_create_by!(name: '日土人', kana: 'ひとびと', company: c)
Brand.find_or_create_by!(name: '櫻朶', kana: 'さくらだ', company: c)
Brand.find_or_create_by!(name: '船中八策', kana: 'せんちゅうはっさく', company: c)
Brand.find_or_create_by!(name: '司牡丹', kana: 'つかさぼたん', company: c)
Brand.find_or_create_by!(name: 'かまわぬ', kana: 'かまわぬ', company: c)
c = Company.create_or_find_by!(name: '西岡酒造店', kana: 'にしおかしゅぞうてん', prefecture_code: 39, city: '高岡郡', address: '中土佐町久礼6154', tel: '0889-52-2018', fax: '0889-52-4526', website: 'http://www.jyunpei.co.jp')
Brand.find_or_create_by!(name: '雪柳', kana: 'ゆきやなぎ', company: c)
Brand.find_or_create_by!(name: 'てっぺん四万十', kana: 'てっぺんしまんと', company: c)
Brand.find_or_create_by!(name: '雲の上の雫', kana: 'くものうえのしずく', company: c)
Brand.find_or_create_by!(name: '久礼', kana: 'くれ', company: c)
Brand.find_or_create_by!(name: '純平', kana: 'じゅんぺい', company: c)
Brand.find_or_create_by!(name: '須崎', kana: 'すさき', company: c)
